import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  
  const translations = {
    en: {
      // Navigation
      home: "Home",
      about: "About",
      profile: "Profile",
      admin: "Admin",
      login: "Login",
      register: "Register",
      logout: "Logout",
      learnMore: "Learn More",
      
      // Hero Section
      heroTitle: "Smart Farming Solutions for Karnataka",
      heroSubtitle: "Get personalized crop recommendations, find quality seeds, and locate agricultural stores near you",
      getStarted: "Get Started",
      
      // Features
      features: "Why Choose Our Platform?",
      feature1Title: "Crop Recommendation",
      feature1Desc: "Get personalized crop suggestions based on soil type, weather conditions, and location",
      feature2Title: "Seed Information",
      feature2Desc: "Access detailed information about different seed varieties and their characteristics",
      feature3Title: "Store Locator",
      feature3Desc: "Find nearby agricultural stores and get directions",
      feature4Title: "Yield Analysis",
      feature4Desc: "Track and analyze your crop yields over time",
      
      // Quick Actions
      quickActions: "Get Started Now",
      action1Title: "Get Crop Recommendations",
      action1Desc: "Find the best crops for your farm",
      action2Title: "Find Seeds",
      action2Desc: "Discover suitable seed varieties",
      action3Title: "Locate Stores",
      action3Desc: "Find agricultural stores near you",
      
      // Crop Recommendation
      cropRecommendation: "Crop Recommendation",
      recommendationDesc: "Get personalized recommendations based on your farm location and conditions",
      cropTab: "Crop Recommendation",
      seedTab: "Seed Finder",
      storeTab: "Store Locator",
      authRequired: "Authentication Required",
      loginMessage: "Please register or login to access crop recommendations",
      
      // Seed Recommendation
      seedRecommendation: "Seed Recommendation",
      cropName: "Crop Name",
      enterCropName: "Enter crop name (e.g., Groundnut, Cotton, Paddy)",
      findSeeds: "Find Seeds",
      seedVarieties: "Seed Varieties",
      type: "Type",
      brand: "Brand",
      price: "Price",
      germination: "Germination Rate",
      duration: "Duration",
      features: "Features",
      contactSupplier: "Contact Supplier",
      
      // Store Recommendation
      storeRecommendation: "Store Locator",
      district: "District",
      selectDistrict: "Select your district",
      storeType: "Store Type",
      selectType: "All Types",
      findStores: "Find Stores",
      noStoresFound: "No stores found for your selection",
      address: "Address",
      contact: "Contact",
      
      // Profile
      personalInfo: "Personal Information",
      name: "Name",
      email: "Email",
      phone: "Phone",
      soilType: "Soil Type",
      recommendationHistory: "Recommendation History",
      history: "History",
      details: "Details",
      settings: "Settings",
      
      // Admin
      dashboard: "Dashboard",
      totalUsers: "Total Users",
      recommendations: "Recommendations",
      crops: "Active Crops",
      stores: "Registered Stores",
      quickActions: "Quick Actions",
      manageUsers: "Manage Users",
      manageCrops: "Manage Crops",
      manageStores: "Manage Stores",
      users: "Users",
      
      // Auth
      fullName: "Full Name",
      password: "Password",
      confirmPassword: "Confirm Password",
      region: "Region",
      alreadyAccount: "Already have an account?",
      noAccount: "Don't have an account?",
      registerHere: "Register here",
      loginHere: "Login here",
      
      // Crop Recommendation Form
      enterDetails: "Enter Your Farm Details",
      selectSoil: "Select soil type",
      selectRainfall: "Select rainfall range",
      temperature: "Temperature (°C)",
      rainfall: "Expected Rainfall (mm)",
      recommendedCrops: "Recommended Crops",
      cropName: "Crop Name",
      expectedYield: "Expected Yield (kg/acre)",
      bestSeason: "Best Season",
      waterRequirements: "Water Requirements",
      harvestDays: "Days to Harvest",
      profitMargin: "Profit Margin",
      
      // Admin Dashboard
      adminDashboard: "Admin Dashboard",
      logoutBtn: "Logout",
      totalUsers: "Total Users",
      totalCrops: "Total Crops",
      totalStores: "Total Stores",
      seedsStat: "Seeds",
      manageContent: "Manage Content",
      addCrop: "Add Crop",
      addSeed: "Add Seed",
      addStore: "Add Store",
      
      // User Management
      userName: "User Name",
      userEmail: "User Email",
      userStatus: "User Status",
      joinDate: "Join Date",
      lastActive: "Last Active",
      userRole: "User Role",
      farmer: "Farmer",
      admin: "Admin",
      active: "Active",
      inactive: "Inactive",
      blocked: "Blocked",
      
      // Profile Page
      profileDetails: "Profile Details",
      farmLocation: "Farm Location",
      farmSize: "Farm Size",
      primaryCrop: "Primary Crop",
      soilInfo: "Soil Information",
      contactInfo: "Contact Information",
      location: "Location",
      state: "State",
      city: "City",
      
      // Crop Details
      soilTypeInfo: "Soil Type",
      harvestSeason: "Harvest Season",
      waterNeed: "Water Need",
      fertilizer: "Fertilizer",
      pestControl: "Pest Control",
      diseasePrevention: "Disease Prevention",
      yieldPotential: "Yield Potential",
      marketPrice: "Market Price",
      transportationCost: "Transportation Cost",
      storageInfo: "Storage Information",
      processingRequired: "Processing Required",
      
      // Seed Details
      seedBrand: "Seed Brand",
      seedType: "Seed Type",
      purityLevel: "Purity Level",
      viability: "Viability",
      packSize: "Pack Size",
      expiryDate: "Expiry Date",
      stockAvailable: "Stock Available",
      supplierInfo: "Supplier Information",
      minimumOrder: "Minimum Order",
      deliveryTime: "Delivery Time",
      
      // Store Details
      storeName: "Store Name",
      storeAddress: "Store Address",
      storePhone: "Store Phone",
      storeEmail: "Store Email",
      storeHours: "Store Hours",
      openingTime: "Opening Time",
      closingTime: "Closing Time",
      productsAvailable: "Products Available",
      deliveryAvailable: "Delivery Available",
      onlineOrdering: "Online Ordering",
      
      // Messages & Alerts
      failedLoadRecommendations: "Failed to get recommendations. Please try again.",
      noDataFound: "No data found",
      tryAgain: "Try Again",
      loading: "Loading...",
      loadingData: "Loading data...",
      dataLoading: "Please wait, data is loading...",
      
      // Form Fields
      submit: "Submit",
      submitForm: "Submit Form",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      update: "Update",
      search: "Search",
      filter: "Filter",
      error: "Error",
      success: "Success",
      warning: "Warning",
      info: "Info",
      close: "Close",
      confirm: "Confirm",
      apply: "Apply",
      reset: "Reset",
      clear: "Clear",
      
      // Headers & Titles
      welcomeBack: "Welcome Back!",
      dashboard: "Dashboard",
      myProfile: "My Profile",
      settings: "Settings",
      help: "Help",
      faq: "FAQ",
      contactUs: "Contact Us",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
      
      // Buttons & Common
      submit: "Submit",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      search: "Search",
      filter: "Filter",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      match: "Match",
      season: "Season",
    },
    kn: {
      // Navigation
      home: "ಮುಖಪುಟ",
      about: "ನಿಮ್ಮ ಬಗ್ಗೆ",
      profile: "ಪ್ರೊಫೈಲ್",
      admin: "ನಿರ್ವಾಹಕ",
      login: "ಲಾಗಿನ್",
      register: "ನೋಂದಣಿ",
      logout: "ಲಾಗ್ ಔಟ್",
      learnMore: "ಹೆಚ್ಚು ತಿಳಿದುಕೊಳ್ಳಿ",
      
      // Hero Section
      heroTitle: "ಕರ್ನಾಟಕಕ್ಕೆ ಸ್ಮಾರ್ಟ ಕೃಷಿ ಪರಿಹಾರ",
      heroSubtitle: "ವ್ಯಕ್ತಿಗತ ಫಸಲು ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ, ಗುಣಮಾನದ ಬೀಜಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ನಿಮ್ಮ ಸಮೀಪವಿದ್ದ ಕೃಷಿ ಮಳಿಗೆಯನ್ನು ಸ್ಥಾನೀಯಗೊಳಿಸಿ",
      getStarted: "ಪ್ರಾರಂಭಿಸಿ",
      
      // Features
      features: "ನಮ್ಮ ವೇದಿಕೆಯನ್ನು ಏಕೆ ಆಯ್ಕೆ ಮಾಡಿ?",
      feature1Title: "ಫಸಲು ಶಿಫಾರಸು",
      feature1Desc: "ಮಣ್ಣಿನ ಪ್ರಕಾರ, ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿ ಮತ್ತು ಸ್ಥಳವನ್ನು ಆಧಾರವಾಗಿಟ್ಟುಕೊಂಡು ವ್ಯಕ್ತಿಗತ ಫಸಲು ಸಲಹೆ ಪಡೆಯಿರಿ",
      feature2Title: "ಬೀಜ ಮಾಹಿತಿ",
      feature2Desc: "ವಿವಿಧ ಬೀಜ ಪ್ರಭೇದ ಮತ್ತು ಅವುಗಳ ಗುಣಲಕ್ಷಣಗಳ ಬಗ್ಗೆ ವಿವರವಾದ ಮಾಹಿತಿ ಪಡೆಯುವಿರಿ",
      feature3Title: "ಮಳಿಗೆ ಸ್ಥಾನೀಯತೆ",
      feature3Desc: "ಹತ್ತಿರದ ಕೃಷಿ ಮಳಿಗೆಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ನಿರ್ದೇಶನ ಪಡೆಯುವಿರಿ",
      feature4Title: "ಇಳುವರಿ ವಿಶ್ಲೇಷಣೆ",
      feature4Desc: "ನಿಮ್ಮ ಫಸಲು ಇಳುವರಿಯನ್ನು ಕಾಲಿನೊಂದಿಗೆ ಟ್ರ್যಾಕ್ ಮಾಡಿ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ ಮಾಡಿ",
      
      // Quick Actions
      quickActions: "ಈಗ ಪ್ರಾರಂಭಿಸಿ",
      action1Title: "ಫಸಲು ಶಿಫಾರಸು ಪಡೆಯಿರಿ",
      action1Desc: "ನಿಮ್ಮ ಜಮೀನಿಗೆ ಉತ್ತಮ ಫಸಲುಗಳನ್ನು ಹುಡುಕಿ",
      action2Title: "ಬೀಜಗಳನ್ನು ಹುಡುಕಿ",
      action2Desc: "ಸೂಕ್ತ ಬೀಜ ಪ್ರಭೇದಗಳನ್ನು ಆವಿಷ್ಕರಿಸಿ",
      action3Title: "ಮಳಿಗೆಯನ್ನು ಸ್ಥಾನೀಯಗೊಳಿಸಿ",
      action3Desc: "ನಿಮ್ಮ ಸಮೀಪವಿದ್ದ ಕೃಷಿ ಮಳಿಗೆಗಳನ್ನು ಹುಡುಕಿ",
      
      // Crop Recommendation
      cropRecommendation: "ಫಸಲು ಶಿಫಾರಸು",
      recommendationDesc: "ನಿಮ್ಮ ಜಮೀನಿನ ಸ್ಥಳ ಮತ್ತು ಪರಿಸ್ಥಿತಿಗಳ ಆಧಾರದ ಮೇಲೆ ವ್ಯಕ್ತಿಗತ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ",
      cropTab: "ಫಸಲು ಶಿಫಾರಸು",
      seedTab: "ಬೀಜ ಹುಡುಕಾಟ",
      storeTab: "ಮಳಿಗೆ ಸ್ಥಾನೀಯತೆ",
      authRequired: "ಪ್ರಮಾಣೀಕರಣ ಬೇಕಾಗಿದೆ",
      loginMessage: "ಫಸಲು ಶಿಫಾರಸುಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ದಯವಿಟ್ಟು ನೋಂದಣಿ ಅಥವಾ ಲಾಗಿನ್ ಮಾಡಿ",
      
      // Seed Recommendation
      seedRecommendation: "ಬೀಜ ಶಿಫಾರಸು",
      cropName: "ಫಸಲಿನ ಹೆಸರು",
      enterCropName: "ಫಸಲಿನ ಹೆಸರನ್ನು ನಮೂದಿಸಿ (ಉದಾ, ಬೇಸವಳೆ, ಪಟ್ಟ, ನೆರೆತೇಪ್ಪಾಲಿ)",
      findSeeds: "ಬೀಜಗಳನ್ನು ಹುಡುಕಿ",
      seedVarieties: "ಬೀಜ ಪ್ರಭೇದಗಳು",
      type: "ಪ್ರಕಾರ",
      brand: "ಬ್ರ್ಯಾಂಡ್",
      price: "ಬೆಲೆ",
      germination: "ಬೀಜ ಅಂಕುರಣ ದರ",
      duration: "ಅವಧಿ",
      features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
      contactSupplier: "ಪೂರೈಕೆದಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ",
      
      // Store Recommendation
      storeRecommendation: "ಮಳಿಗೆ ಸ್ಥಾನೀಯತೆ",
      district: "ಜಿಲ್ಲೆ",
      selectDistrict: "ನಿಮ್ಮ ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
      storeType: "ಮಳಿಗೆ ಪ್ರಕಾರ",
      selectType: "ಎಲ್ಲಾ ಪ್ರಕಾರಗಳು",
      findStores: "ಮಳಿಗೆಗಳನ್ನು ಹುಡುಕಿ",
      noStoresFound: "ನಿಮ್ಮ ಆಯ್ಕೆಗೆ ಮಳಿಗೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
      address: "ವಿಳಾಸ",
      contact: "ಸಂಪರ್ಕ",
      
      // Profile
      personalInfo: "ವ್ಯಕ್ತಿಗತ ಮಾಹಿತಿ",
      name: "ಹೆಸರು",
      email: "ಇಮೇಲ್",
      phone: "ಫೋನ್",
      soilType: "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
      recommendationHistory: "ಶಿಫಾರಸು ಇತಿಹಾಸ",
      history: "ಇತಿಹಾಸ",
      details: "ವಿವರಣೆ",
      settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
      
      // Admin
      dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
      totalUsers: "ಒಟ್ಟು ಬಳಕೆದಾರರು",
      recommendations: "ಶಿಫಾರಸುಗಳು",
      crops: "ಸಕ್ರಿಯ ಫಸಲುಗಳು",
      stores: "ನೋಂದಾಯಿತ ಮಳಿಗೆಗಳು",
      quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
      manageUsers: "ಬಳಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ",
      manageCrops: "ಫಸಲುಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
      manageStores: "ಮಳಿಗೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
      users: "ಬಳಕೆದಾರರು",
      
      // Auth
      fullName: "ಪೂರ್ಣ ಹೆಸರು",
      password: "ಪಾಸ್ವರ್ಡ್",
      confirmPassword: "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
      region: "ಪ್ರದೇಶ",
      alreadyAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?",
      noAccount: "ಖಾತೆ ಹೊಂದಿಲ್ಲವೇ?",
      registerHere: "ಇಲ್ಲಿ ನೋಂದಣಿ ಮಾಡಿ",
      loginHere: "ಇಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ",
      
      // Crop Recommendation Form
      enterDetails: "ನಿಮ್ಮ ಜಮೀನಿನ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
      selectSoil: "ಮಣ್ಣಿನ ಪ್ರಕಾರ ಆಯ್ಕೆ ಮಾಡಿ",
      selectRainfall: "ವರ್ಷಾಂಶ ಶ್ರೇಣಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
      temperature: "ತಾಪಮಾನ (°C)",
      rainfall: "ನಿರೀಕ್ಷಿತ ವರ್ಷಾಕಾಲ (ಮಿಮೀ)",
      recommendedCrops: "ಶಿಫಾರಸಿತ ಫಸಲುಗಳು",
      cropName: "ಫಸಲಿನ ಹೆಸರು",
      expectedYield: "ನಿರೀಕ್ಷಿತ ಇಳುವರಿ (ಕೆಜಿ/ಎಕರೆ)",
      bestSeason: "ಅತ್ಯುತ್ತಮ ಋತು",
      waterRequirements: "ನೀರಿನ ಅವಶ್ಯಕತೆ",
      harvestDays: "ಸುಗ್ರಹಿಕೆ ಗಳಿಕೆ ಗಳಿಗೆ ದಿನಗಳು",
      profitMargin: "ಲಾಭ ಅಂತರ",
      
      // Admin Dashboard
      adminDashboard: "ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
      logoutBtn: "ಲಾಗ್ ಔಟ್",
      totalUsers: "ಒಟ್ಟು ಬಳಕೆದಾರರು",
      totalCrops: "ಒಟ್ಟು ಫಸಲುಗಳು",
      totalStores: "ಒಟ್ಟು ಮಳಿಗೆಗಳು",
      seedsStat: "ಬೀಜಗಳು",
      manageContent: "ವಿಷಯವನ್ನು ನಿರ್ವಹಿಸಿ",
      addCrop: "ಫಸಲನ್ನು ಸೇರಿಸಿ",
      addSeed: "ಬೀಜವನ್ನು ಸೇರಿಸಿ",
      addStore: "ಮಳಿಗೆಯನ್ನು ಸೇರಿಸಿ",
      
      // User Management
      userName: "ಬಳಕೆದಾರರ ಹೆಸರು",
      userEmail: "ಬಳಕೆದಾರರ ಇಮೇಲ್",
      userStatus: "ಬಳಕೆದಾರರ ಸ್ಥಿತಿ",
      joinDate: "ಸೇರುವ ದಿನಾಂಕ",
      lastActive: "ಕೊನೆಯ ಸಕ್ರಿಯ",
      userRole: "ಬಳಕೆದಾರರ ಪಾತ್ರ",
      farmer: "ರೈತ",
      admin: "ನಿರ್ವಾಹಕ",
      active: "ಸಕ್ರಿಯ",
      inactive: "ನಿಷ್ಕ್ರಿಯ",
      blocked: "ನಿರ್ಬಂಧಿತ",
      
      // Profile Page
      profileDetails: "ಪ್ರೊಫೈಲ್ ವಿವರಣೆ",
      farmLocation: "ಜಮೀನಿನ ಸ್ಥಳ",
      farmSize: "ಜಮೀನಿನ ಗಾತ್ರ",
      primaryCrop: "ಪ್ರಧಾನ ಫಸಲು",
      soilInfo: "ಮಣ್ಣಿನ ಮಾಹಿತಿ",
      contactInfo: "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
      location: "ಸ್ಥಳ",
      state: "ರಾಜ್ಯ",
      city: "ನಗರ",
      
      // Crop Details
      soilTypeInfo: "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
      harvestSeason: "ಸುಗ್ರಹಿಕೆ ಋತು",
      waterNeed: "ನೀರಿನ ಅವಶ್ಯಕತೆ",
      fertilizer: "ಗೊಬರು",
      pestControl: "ಕೀಟ ನಿಯಂತ್ರಣ",
      diseasePrevention: "ರೋಗ ತಡೆ",
      yieldPotential: "ಇಳುವರಿ ಸಾಮರ್ಥ್ಯ",
      marketPrice: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ",
      transportationCost: "ಸರಿಸಾಮಗ್ರಿ ವೆಚ್ಚ",
      storageInfo: "ಸಂಗ್ರಹಣ ಮಾಹಿತಿ",
      processingRequired: "ಸಂಸ್ಕರಣೆ ಅವಶ್ಯಕ",
      
      // Seed Details
      seedBrand: "ಬೀಜ ಬ್ರ್ಯಾಂಡ್",
      seedType: "ಬೀಜ ಪ್ರಕಾರ",
      purityLevel: "ಶುದ್ಧತೆ ಮಟ್ಟ",
      viability: "ಆಜೀವನತ್ವ",
      packSize: "ಪ್ಯಾಕ್ ಗಾತ್ರ",
      expiryDate: "ಅವಧಿ ಮುಗಿಯುವ ದಿನಾಂಕ",
      stockAvailable: "ಸ್ಟಾಕ್ ಲಭ್ಯತೆ",
      supplierInfo: "ಪೂರೈಕೆದಾರರ ಮಾಹಿತಿ",
      minimumOrder: "ಕನಿಷ್ಠ ಆದೇಶ",
      deliveryTime: "ವಿತರಣ ಸಮಯ",
      
      // Store Details
      storeName: "ಮಳಿಗೆ ಹೆಸರು",
      storeAddress: "ಮಳಿಗೆ ವಿಳಾಸ",
      storePhone: "ಮಳಿಗೆ ಫೋನ್",
      storeEmail: "ಮಳಿಗೆ ಇಮೇಲ್",
      storeHours: "ಮಳಿಗೆ ಗಂಟೆಗಳು",
      openingTime: "ಪ್ರಾರಂಭ ಸಮಯ",
      closingTime: "ಸಮಾಪ್ತ ಸಮಯ",
      productsAvailable: "ಲಭ್ಯ ಉತ್ಪನ್ನಗಳು",
      deliveryAvailable: "ವಿತರಣ ಲಭ್ಯತೆ",
      onlineOrdering: "ಆನ್ಲೈನ್ ಆದೇಶ",
      
      // Messages & Alerts
      failedLoadRecommendations: "ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ವಿಫಲ. ಮತ್ತೆ ಪ್ರಯತ್ನ ಮಾಡಿ.",
      noDataFound: "ಡೇಟಾ ಕಂಡುಬಂದಿಲ್ಲ",
      tryAgain: "ಮತ್ತೆ ಪ್ರಯತ್ನ ಮಾಡಿ",
      loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
      loadingData: "ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
      dataLoading: "ದಯವಿಟ್ಟು ಹೋಕುಳಿ ಬಿಡಿ, ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
      
      // Form Fields
      submit: "ಸಲ್ಲಿಸಿ",
      submitForm: "ಫಾರ್ಮ್ ಸಲ್ಲಿಸಿ",
      cancel: "ರದ್ದು ಮಾಡಿ",
      save: "ಉಳಿಸಿ",
      delete: "ಅಳಿಸಿ",
      edit: "ಸಂಪಾದನೆ",
      update: "ನವೀಕರಣ",
      search: "ಹುಡುಕಾಟ",
      filter: "ಸೋಸಣೆ",
      error: "ದೋಷ",
      success: "ಯಶಸ್ಸು",
      warning: "ಎಚ್ಚರಿಕೆ",
      info: "ಮಾಹಿತಿ",
      close: "ಮುಚ್ಚಿ",
      confirm: "ದೃಢೀಕರಿಸಿ",
      apply: "ಅನ್ವಯಿಸಿ",
      reset: "ಮರುಹೊಂದಿಸಿ",
      clear: "ಸ್ಪಷ್ಟ",
      
      // Headers & Titles
      welcomeBack: "ಸ್ವಾಗತ!",
      dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
      myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
      settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
      help: "ಸಹಾಯತೆ",
      faq: "ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು",
      contactUs: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
      about: "ನಮ್ಮ ಬಗ್ಗೆ",
      privacy: "ಗೌಪ್ಯತೆ ನೀತಿ",
      terms: "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
      
      // Buttons & Common
      submit: "ಸಲ್ಲಿಸಿ",
      cancel: "ರದ್ದು ಮಾಡಿ",
      save: "ಉಳಿಸಿ",
      delete: "ಅಳಿಸಿ",
      edit: "ಸಂಪಾದನೆ",
      search: "ಹುಡುಕಾಟ",
      filter: "ಸೋಸಣೆ",
      loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
      error: "ದೋಷ",
      success: "ಯಶಸ್ಸು",
      match: "ಹೊಂದಿಕೆ",
      season: "ಋತು",
    },
    hi: {
      // Navigation
      home: "होम",
      about: "परिचय",
      profile: "प्रोफाइल",
      admin: "प्रशासक",
      login: "लॉगिन करें",
      register: "पंजीकरण करें",
      logout: "लॉगआउट",
      learnMore: "अधिक जानें",
      
      // Hero Section
      heroTitle: "कर्नाटक के लिए स्मार्ट खेती समाधान",
      heroSubtitle: "व्यक्तिगत फसल सिफारिशें प्राप्त करें, गुणवत्ता वाले बीज खोजें और आपके पास कृषि दुकानों का पता लगाएं",
      getStarted: "शुरुआत करें",
      
      // Features
      features: "हमारे प्लेटफॉर्म को क्यों चुनें?",
      feature1Title: "फसल सिफारिश",
      feature1Desc: "मिट्टी के प्रकार, मौसम की स्थिति और स्थान के आधार पर व्यक्तिगत फसल सुझाव प्राप्त करें",
      feature2Title: "बीज जानकारी",
      feature2Desc: "विभिन्न बीज किस्मों और उनकी विशेषताओं के बारे में विस्तृत जानकारी प्राप्त करें",
      feature3Title: "दुकान लोकेटर",
      feature3Desc: "पास के कृषि दुकानें खोजें और निर्देश प्राप्त करें",
      feature4Title: "उपज विश्लेषण",
      feature4Desc: "समय के साथ अपनी फसल की पैदावार को ट्रैक और विश्लेषण करें",
      
      // Quick Actions
      quickActions: "अभी शुरुआत करें",
      action1Title: "फसल सिफारिश प्राप्त करें",
      action1Desc: "अपनी जमीन के लिए सर्वश्रेष्ठ फसलें खोजें",
      action2Title: "बीज खोजें",
      action2Desc: "उपयुक्त बीज किस्में खोजें",
      action3Title: "दुकान स्थानीयकरण करें",
      action3Desc: "आपके पास कृषि दुकानें खोजें",
      
      // Crop Recommendation
      cropRecommendation: "फसल सिफारिश",
      recommendationDesc: "अपनी जमीन की स्थान और परिस्थितियों के आधार पर व्यक्तिगत सिफारिशें प्राप्त करें",
      cropTab: "फसल सिफारिश",
      seedTab: "बीज फाइंडर",
      storeTab: "दुकान लोकेटर",
      authRequired: "प्रमाणीकरण आवश्यक है",
      loginMessage: "फसल सिफारिशों तक पहुंचने के लिए कृपया पंजीकरण करें या लॉगिन करें",
      
      // Seed Recommendation
      seedRecommendation: "बीज सिफारिश",
      cropName: "फसल का नाम",
      enterCropName: "फसल का नाम दर्ज करें (जैसे, मूंगफली, कपास, चावल)",
      findSeeds: "बीज खोजें",
      seedVarieties: "बीज किस्में",
      type: "प्रकार",
      brand: "ब्रांड",
      price: "कीमत",
      germination: "अंकुरण दर",
      duration: "अवधि",
      features: "विशेषताएं",
      contactSupplier: "आपूर्तिकर्ता से संपर्क करें",
      
      // Store Recommendation
      storeRecommendation: "दुकान लोकेटर",
      district: "जिला",
      selectDistrict: "अपने जिले का चयन करें",
      storeType: "दुकान का प्रकार",
      selectType: "सभी प्रकार",
      findStores: "दुकानें खोजें",
      noStoresFound: "आपके चयन के लिए कोई दुकान नहीं मिली",
      address: "पता",
      contact: "संपर्क",
      
      // Profile
      personalInfo: "व्यक्तिगत जानकारी",
      name: "नाम",
      email: "ईमेल",
      phone: "फोन",
      soilType: "मिट्टी का प्रकार",
      recommendationHistory: "सिफारिश का इतिहास",
      history: "इतिहास",
      details: "विवरण",
      settings: "सेटिंग्स",
      
      // Admin
      dashboard: "डैशबोर्ड",
      totalUsers: "कुल उपयोगकर्ता",
      recommendations: "सिफारिशें",
      crops: "सक्रिय फसलें",
      stores: "पंजीकृत दुकानें",
      quickActions: "त्वरित कार्य",
      manageUsers: "उपयोगकर्ताओं को प्रबंधित करें",
      manageCrops: "फसलों को प्रबंधित करें",
      manageStores: "दुकानों को प्रबंधित करें",
      users: "उपयोगकर्ता",
      
      // Auth
      fullName: "पूरा नाम",
      password: "पासवर्ड",
      confirmPassword: "पासवर्ड की पुष्टि करें",
      region: "क्षेत्र",
      alreadyAccount: "पहले से खाता है?",
      noAccount: "खाता नहीं है?",
      registerHere: "यहां पंजीकरण करें",
      loginHere: "यहां लॉगिन करें",
      
      // Crop Recommendation Form
      enterDetails: "अपने खेत का विवरण दर्ज करें",
      selectSoil: "मिट्टी का प्रकार चुनें",
      selectRainfall: "वर्षा सीमा चुनें",
      temperature: "तापमान (°C)",
      rainfall: "अपेक्षित वर्षा (मिमी)",
      recommendedCrops: "अनुशंसित फसलें",
      cropName: "फसल का नाम",
      expectedYield: "अपेक्षित उपज (किग्रा/एकड़)",
      bestSeason: "सर्वश्रेष्ठ मौसम",
      waterRequirements: "जल आवश्यकता",
      harvestDays: "कटाई के दिन",
      profitMargin: "लाभ मार्जिन",
      
      // Admin Dashboard
      adminDashboard: "प्रशासक डैशबोर्ड",
      logoutBtn: "लॉगआउट",
      totalUsers: "कुल उपयोगकर्ता",
      totalCrops: "कुल फसलें",
      totalStores: "कुल दुकानें",
      seedsStat: "बीज",
      manageContent: "सामग्री प्रबंधित करें",
      addCrop: "फसल जोड़ें",
      addSeed: "बीज जोड़ें",
      addStore: "दुकान जोड़ें",
      
      // User Management
      userName: "उपयोगकर्ता नाम",
      userEmail: "उपयोगकर्ता ईमेल",
      userStatus: "उपयोगकर्ता स्थिति",
      joinDate: "शामिल होने की तारीख",
      lastActive: "अंतिम सक्रिय",
      userRole: "उपयोगकर्ता भूमिका",
      farmer: "किसान",
      admin: "प्रशासक",
      active: "सक्रिय",
      inactive: "निष्क्रिय",
      blocked: "अवरुद्ध",
      
      // Profile Page
      profileDetails: "प्रोफाइल विवरण",
      farmLocation: "खेत का स्थान",
      farmSize: "खेत का आकार",
      primaryCrop: "प्राथमिक फसल",
      soilInfo: "मिट्टी की जानकारी",
      contactInfo: "संपर्क जानकारी",
      location: "स्थान",
      state: "राज्य",
      city: "शहर",
      
      // Crop Details
      soilTypeInfo: "मिट्टी का प्रकार",
      harvestSeason: "कटाई का मौसम",
      waterNeed: "जल की आवश्यकता",
      fertilizer: "खाद",
      pestControl: "कीट नियंत्रण",
      diseasePrevention: "रोग की रोकथाम",
      yieldPotential: "उपज क्षमता",
      marketPrice: "बाजार मूल्य",
      transportationCost: "परिवहन लागत",
      storageInfo: "भंडारण जानकारी",
      processingRequired: "प्रसंस्करण आवश्यक",
      
      // Seed Details
      seedBrand: "बीज ब्रांड",
      seedType: "बीज प्रकार",
      purityLevel: "शुद्धता स्तर",
      viability: "व्यवहार्यता",
      packSize: "पैक साइज",
      expiryDate: "समाप्ति तारीख",
      stockAvailable: "स्टॉक उपलब्ध",
      supplierInfo: "आपूर्तिकर्ता जानकारी",
      minimumOrder: "न्यूनतम ऑर्डर",
      deliveryTime: "डिलीवरी समय",
      
      // Store Details
      storeName: "दुकान का नाम",
      storeAddress: "दुकान का पता",
      storePhone: "दुकान फोन",
      storeEmail: "दुकान ईमेल",
      storeHours: "दुकान के घंटे",
      openingTime: "खुलने का समय",
      closingTime: "बंद होने का समय",
      productsAvailable: "उपलब्ध उत्पाद",
      deliveryAvailable: "डिलीवरी उपलब्ध",
      onlineOrdering: "ऑनलाइन ऑर्डरिंग",
      
      // Messages & Alerts
      failedLoadRecommendations: "सिफारिशें प्राप्त करने में विफल। कृपया पुनः प्रयास करें।",
      noDataFound: "कोई डेटा नहीं मिला",
      tryAgain: "फिर से प्रयास करें",
      loading: "लोड हो रहा है...",
      loadingData: "डेटा लोड हो रहा है...",
      dataLoading: "कृपया प्रतीक्षा करें, डेटा लोड हो रहा है...",
      
      // Form Fields
      submit: "सबमिट करें",
      submitForm: "फॉर्म सबमिट करें",
      cancel: "रद्द करें",
      save: "बचाएं",
      delete: "हटाएं",
      edit: "संपादित करें",
      update: "अपडेट करें",
      search: "खोज",
      filter: "फ़िल्टर",
      error: "त्रुटि",
      success: "सफल",
      warning: "चेतावनी",
      info: "जानकारी",
      close: "बंद करें",
      confirm: "पुष्टि करें",
      apply: "लागू करें",
      reset: "रीसेट करें",
      clear: "साफ़ करें",
      
      // Headers & Titles
      welcomeBack: "स्वागत है!",
      dashboard: "डैशबोर्ड",
      myProfile: "मेरी प्रोफाइल",
      settings: "सेटिंग्स",
      help: "मदद",
      faq: "सामान्य प्रश्न",
      contactUs: "हमसे संपर्क करें",
      about: "हमारे बारे में",
      privacy: "गोपनीयता नीति",
      terms: "शर्तें और शिकायतें",
      
      // Buttons & Common
      submit: "सबमिट करें",
      cancel: "रद्द करें",
      save: "बचाएं",
      delete: "हटाएं",
      edit: "संपादित करें",
      search: "खोज",
      filter: "फ़िल्टर",
      loading: "लोड हो रहा है...",
      error: "त्रुटि",
      success: "सफल",
      match: "मिलान",
      season: "मौसम",
    },
    mr: {
      // Navigation
      home: "होम",
      about: "माहिती",
      profile: "प्रोफाइल",
      admin: "प्रशासक",
      login: "लॉगिन करा",
      register: "नोंदणी करा",
      logout: "लॉगआउट",
      learnMore: "अधिक जाणून घ्या",
      
      // Hero Section
      heroTitle: "कर्नाटकासाठी स्मार्ट शेतीतील उपाय",
      heroSubtitle: "व्यक्तिगत पीक शिफारसी मिळवा, गुणवत्तेची बिया शोधा आणि तुमच्या जवळील कृषी दुकानांचे स्थान शोधा",
      getStarted: "सुरुवात करा",
      
      // Features
      features: "आमचा प्लॅटफॉर्म का निवडावा?",
      feature1Title: "पीक शिफारस",
      feature1Desc: "मातीचा प्रकार, हवामान परिस्थिती आणि स्थान यावर आधारित व्यक्तिगत पीक सुझाव मिळवा",
      feature2Title: "बियाची माहिती",
      feature2Desc: "विविध बियाच्या जातींबद्दल आणि त्यांच्या वैशिष्ट्यांबद्दल तपशीली माहिती मिळवा",
      feature3Title: "दुकान शोधक",
      feature3Desc: "जवळ्यातील कृषी दुकाने शोधा आणि दिशानिर्देश मिळवा",
      feature4Title: "उत्पादन विश्लेषण",
      feature4Desc: "कालांतराने आपली पीकांची उत्पादकता ट्रॅक आणि विश्लेषण करा",
      
      // Quick Actions
      quickActions: "आता सुरुवात करा",
      action1Title: "पीक शिफारस मिळवा",
      action1Desc: "आपल्या शेतासाठी सर्वोत्तम पीक शोधा",
      action2Title: "बिया शोधा",
      action2Desc: "उपयुक्त बियाच्या जाती शोधा",
      action3Title: "दुकान स्थानीयकरण करा",
      action3Desc: "तुमच्या जवळील कृषी दुकाने शोधा",
      
      // Crop Recommendation
      cropRecommendation: "पीक शिफारस",
      recommendationDesc: "आपल्या शेताच्या स्थान आणि परिस्थितीवर आधारित व्यक्तिगत शिफारसी मिळवा",
      cropTab: "पीक शिफारस",
      seedTab: "बिया शोधक",
      storeTab: "दुकान शोधक",
      authRequired: "प्रमाणीकरण आवश्यक आहे",
      loginMessage: "पीक शिफारसीमध्ये प्रवेश करण्यासाठी कृपया नोंदणी करा किंवा लॉगिन करा",
      
      // Seed Recommendation
      seedRecommendation: "बिया शिफारस",
      cropName: "पीकाचे नाव",
      enterCropName: "पीकाचे नाव टाका (उदा, मूंगफळी, कापूस, तांदूळ)",
      findSeeds: "बिया शोधा",
      seedVarieties: "बियाच्या जातीं",
      type: "प्रकार",
      brand: "ब्रँड",
      price: "किंमत",
      germination: "अंकुरण दर",
      duration: "कालावधी",
      features: "वैशिष्ट्ये",
      contactSupplier: "पूरवठेदारांशी संपर्क साधा",
      
      // Store Recommendation
      storeRecommendation: "दुकान शोधक",
      district: "जिल्हा",
      selectDistrict: "आपला जिल्हा निवडा",
      storeType: "दुकानाचा प्रकार",
      selectType: "सर्व प्रकार",
      findStores: "दुकाने शोधा",
      noStoresFound: "आपल्या निवडीसाठी कोणतीही दुकान आढळली नाही",
      address: "पता",
      contact: "संपर्क",
      
      // Profile
      personalInfo: "व्यक्तिगत माहिती",
      name: "नाव",
      email: "ई-मेल",
      phone: "फोन",
      soilType: "मातीचा प्रकार",
      recommendationHistory: "शिफारस इतिहास",
      history: "इतिहास",
      details: "तपशील",
      settings: "सेटिंग्स",
      
      // Admin
      dashboard: "डॅशबोर्ड",
      totalUsers: "एकूण वापरकर्ता",
      recommendations: "शिफारसी",
      crops: "सक्रिय पीके",
      stores: "नोंदणीकृत दुकाने",
      quickActions: "त्वरित कृती",
      manageUsers: "वापरकर्त्यांचे व्यवस्थापन करा",
      manageCrops: "पीकांचे व्यवस्थापन करा",
      manageStores: "दुकानांचे व्यवस्थापन करा",
      users: "वापरकर्ता",
      
      // Auth
      fullName: "पूर्ण नाव",
      password: "पासवर्ड",
      confirmPassword: "पासवर्डची पुष्टी करा",
      region: "प्रदेश",
      alreadyAccount: "आधीच खाते आहे?",
      noAccount: "खाते नाही?",
      registerHere: "येथे नोंदणी करा",
      loginHere: "येथे लॉगिन करा",
      
      // Crop Recommendation Form
      enterDetails: "आपल्या शेताचे तपशील प्रविष्ट करा",
      selectSoil: "मातीचा प्रकार निवडा",
      selectRainfall: "पर्जन्य श्रेणी निवडा",
      temperature: "तापमान (°C)",
      rainfall: "अपेक्षित पावसाळ (मिमी)",
      recommendedCrops: "शिफारस केलेली पीके",
      cropName: "पीकाचे नाव",
      expectedYield: "अपेक्षित उत्पादन (किग्रा/एकर)",
      bestSeason: "सर्वोत्तम हंगाम",
      waterRequirements: "पाण्याची आवश्यकता",
      harvestDays: "कापणीचे दिवस",
      profitMargin: "नफ्याचा अंतर",
      
      // Admin Dashboard
      adminDashboard: "व्यवस्थापक डॅशबोर्ड",
      logoutBtn: "लॉगआउट",
      totalUsers: "एकूण वापरकर्ता",
      totalCrops: "एकूण पीके",
      totalStores: "एकूण दुकाने",
      seedsStat: "बिया",
      manageContent: "सामग्री व्यवस्थापित करा",
      addCrop: "पीक जोडा",
      addSeed: "बीज जोडा",
      addStore: "दुकान जोडा",
      
      // User Management
      userName: "वापरकर्ता नाव",
      userEmail: "वापरकर्ता ईमेल",
      userStatus: "वापरकर्ता स्थिती",
      joinDate: "सामील होण्याची तारीख",
      lastActive: "शेवटचे सक्रिय",
      userRole: "वापरकर्ता भूमिका",
      farmer: "शेतकरी",
      admin: "व्यवस्थापक",
      active: "सक्रिय",
      inactive: "निष्क्रिय",
      blocked: "अवरोधित",
      
      // Profile Page
      profileDetails: "प्रोफाइल तपशील",
      farmLocation: "शेताचे स्थान",
      farmSize: "शेताचे आकार",
      primaryCrop: "प्राथमिक पीक",
      soilInfo: "माती माहिती",
      contactInfo: "संपर्क माहिती",
      location: "स्थान",
      state: "राज्य",
      city: "शहर",
      
      // Crop Details
      soilTypeInfo: "मातीचा प्रकार",
      harvestSeason: "कापणीचा हंगाम",
      waterNeed: "पाण्याची आवश्यकता",
      fertilizer: "खत",
      pestControl: "कीटक नियंत्रण",
      diseasePrevention: "रोग प्रतिबंधक",
      yieldPotential: "उत्पादन संभावना",
      marketPrice: "बाजार किंमत",
      transportationCost: "वाहतूक खर्च",
      storageInfo: "साठवणूक माहिती",
      processingRequired: "प्रक्रिया आवश्यक",
      
      // Seed Details
      seedBrand: "बिया ब्रँड",
      seedType: "बिया प्रकार",
      purityLevel: "शुद्धता स्तर",
      viability: "जीवनक्षमता",
      packSize: "पॅक आकार",
      expiryDate: "कालांतराची तारीख",
      stockAvailable: "माल उपलब्ध",
      supplierInfo: "पूरवठेदार माहिती",
      minimumOrder: "किमान ऑर्डर",
      deliveryTime: "डिलिव्हरी वेळ",
      
      // Store Details
      storeName: "दुकान नाव",
      storeAddress: "दुकान पता",
      storePhone: "दुकान फोन",
      storeEmail: "दुकान ईमेल",
      storeHours: "दुकान वेळ",
      openingTime: "उघडण्याची वेळ",
      closingTime: "बंद होण्याची वेळ",
      productsAvailable: "उपलब्ध उत्पादने",
      deliveryAvailable: "डिलिव्हरी उपलब्ध",
      onlineOrdering: "ऑनलाइन ऑर्डरिंग",
      
      // Messages & Alerts
      failedLoadRecommendations: "शिफारसी प्राप्त करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
      noDataFound: "कोणताही डेटा आढळला नाही",
      tryAgain: "पुन्हा प्रयत्न करा",
      loading: "लोड होत आहे...",
      loadingData: "डेटा लोड होत आहे...",
      dataLoading: "कृपया प्रतीक्षा करा, डेटा लोड होत आहे...",
      
      // Form Fields
      submit: "सादर करा",
      submitForm: "फॉर्म सादर करा",
      cancel: "रद्द करा",
      save: "जतन करा",
      delete: "हटवा",
      edit: "संपादित करा",
      update: "अद्यतन करा",
      search: "शोध",
      filter: "गाळा",
      error: "त्रुटी",
      success: "यशस्वी",
      warning: "चेतावणी",
      info: "माहिती",
      close: "बंद करा",
      confirm: "खात्रीने सांगा",
      apply: "लागू करा",
      reset: "रीसेट करा",
      clear: "साफ करा",
      
      // Headers & Titles
      welcomeBack: "स्वागत आहे!",
      dashboard: "डॅशबोर्ड",
      myProfile: "माझी प्रोफाइल",
      settings: "सेटिंग्स",
      help: "मदत",
      faq: "सर्वसामान्य प्रश्न",
      contactUs: "आमच्याशी संपर्क साधा",
      about: "आमच्या बद्दल",
      privacy: "गोपनीयता धोरण",
      terms: "अटी व शर्तींची माहिती",
      
      // Buttons & Common
      submit: "सादर करा",
      cancel: "रद्द करा",
      save: "जतन करा",
      delete: "हटवा",
      edit: "संपादित करा",
      search: "शोध",
      filter: "गाळा",
      loading: "लोड होत आहे...",
      error: "त्रुटी",
      success: "यशस्वी",
      match: "जुळणे",
      season: "हंगाम",
    }
  };

  const value = {
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || key
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};