import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const translations = {
    en: {
      // Navigation
      home: "Home",
      about: "About",
      profile: "Profile",
      admin: "Admin",
      login: "Login",
      register: "Register",
      logout: "Logout",
      learnMore: "Learn More",

      // Hero Section
      heroTitle: "Smart Farming Solutions for Karnataka",
      heroSubtitle: "Get personalized crop recommendations, find quality seeds, and locate agricultural stores near you",
      getStarted: "Get Started",
      smartFarmingTechnology: "Smart Farming Technology",
      cropVarieties: "Crop Varieties",
      storesListed: "Stores Listed",
      regionsCovered: "Regions Covered",

      // Features
      features: "Why Choose Our Platform?",
      feature1Title: "Crop Recommendation",
      feature1Desc: "Get personalized crop suggestions based on soil type, weather conditions, and location",
      feature2Title: "Seed Information",
      feature2Desc: "Access detailed information about different seed varieties and their characteristics",
      feature3Title: "Store Locator",
      feature3Desc: "Find nearby agricultural stores and get directions",
      feature4Title: "Yield Analysis",
      feature4Desc: "Track and analyze your crop yields over time",
      whyChooseTitle: "Why Choose Our Platform?",
      whyChooseSubtitle: "Empowering farmers with technology for better crop management",
      smartRecommendationsTitle: "Smart Recommendations",
      smartRecommendationsDesc: "AI-powered suggestions based on soil, climate, and regional data.",
      storeLocatorTitle: "Store Locator",
      storeLocatorDesc: "Find trusted agricultural stores near you with verified reviews.",
      maximizeYieldTitle: "Maximize Yield",
      maximizeYieldDesc: "Optimize crop selection to increase productivity and profits.",
      trustedDataTitle: "Trusted Data",
      trustedDataDesc: "Backed by agricultural research and real farmer experiences.",

      // Quick Actions
      quickActions: "Get Started Now",
      action1Title: "Get Crop Recommendations",
      action1Desc: "Find the best crops for your farm",
      action2Title: "Find Seeds",
      action2Desc: "Discover suitable seed varieties",
      action3Title: "Locate Stores",
      action3Desc: "Find agricultural stores near you",
      readyToStart: "Ready to Get Started?",
      joinFarmers: "Join thousands of farmers making smarter crop decisions every day.",
      getRecommendationBtn: "Get Your Recommendation →",
      footerRights: "Crop Recommendation System — All Rights Reserved",

      // Crop Recommendation
      cropRecommendation: "Crop Recommendation",
      recommendationDesc: "Get personalized recommendations based on your farm location and conditions",
      cropTab: "Crop Recommendation",
      seedTab: "Seed Finder",
      storeTab: "Store Locator",
      authRequired: "Authentication Required",
      loginMessage: "Please register or login to access crop recommendations",
      enterTemp: "Enter temperature",
      match: "Match",
      season: "Season",
      duration: "Duration",
      waterNeeds: "Water Needs",
      fertilizers: "Fertilizers",
      expectedYield: "Expected Yield",
      noDataFound: "No data found",

      // Seed Recommendation
      seedRecommendation: "Seed Recommendation",
      cropName: "Crop Name",
      enterCropName: "Enter crop name (e.g., Groundnut, Cotton, Paddy)",
      findSeeds: "Find Seeds",
      seedVarieties: "Seed Varieties",
      type: "Type",
      brand: "Brand",
      price: "Price",
      germination: "Germination Rate",
      features: "Features",
      contactSupplier: "Contact Supplier",
      quickSelect: "Quick select:",
      for: "for",
      enterCropToFind: "Enter a crop name to find recommended seed varieties.",

      // Store Recommendation
      storeRecommendation: "Store Locator",
      district: "District",
      selectDistrict: "Select District",
      storeType: "Store Type",
      selectType: "All Types",
      findStores: "Find Stores",
      noStoresFound: "No stores found for your selection",
      address: "Address",
      contact: "Contact",
      allStores: "All Stores",
      nearbyStores: "Nearby Stores",
      in: "in",
      govtApproved: "Govt Approved",
      timing: "Timing",
      products: "Products",
      availableSeeds: "Available Seeds:",
      reviews: "reviews",
      noStoresInDistrict: "No stores found in {district}. Try selecting a different district.",
      selectDistrictPrompt: "Please select a district to find nearby stores.",
      getDirections: "Get Directions",
      callStore: "Call Store",

      // Profile
      personalInfo: "Personal Information",
      name: "Name",
      email: "Email",
      phone: "Phone",
      soilType: "Soil Type",
      recommendationHistory: "Recommendation History",
      history: "History",
      details: "Details",
      settings: "Settings",

      // Admin
      dashboard: "Dashboard",
      totalUsers: "Total Users",
      recommendations: "Recommendations",
      crops: "Active Crops",
      stores: "Registered Stores",
      manageUsers: "Manage Users",
      manageCrops: "Manage Crops",
      manageStores: "Manage Stores",
      users: "Users",
      adminPanel: "Admin Panel",
      defaultCredentials: "Default Credentials: admin@gmail.com / admin123",
      registeredUsers: "Registered Users",
      role: "Role",
      actions: "Actions",
      confirmDeleteUser: "Are you sure you want to delete this user?",
      addNewContent: "Add New Content",
      selectContentToAdd: "Select what you want to add to the system",
      addCropDesc: "Add new crop data with requirements",
      addStoreDesc: "Add agricultural stores with contact info",
      addSeedDesc: "Add seed brands with reliability scores",
      backToAll: "Back to All",

      // Auth
      fullName: "Full Name",
      password: "Password",
      confirmPassword: "Confirm Password",
      region: "Region",
      alreadyAccount: "Already have an account?",
      noAccount: "Don't have an account?",
      registerHere: "Register here",
      loginHere: "Login here",
      userLogin: "User Login",
      adminLogin: "Admin Login",
      enterEmail: "Please enter a valid email address.",
      passwordLengthError: "Password must be at least 6 characters.",
      loginFailed: "Login failed",
      loginError: "Login error",
      registerPrompt: "Don't have an account?",
      loginPrompt: "Already have an account?",
      phonePlaceholder: "10-digit phone number",
      regionPlaceholder: "e.g., North Karnataka",
      districtPlaceholder: "e.g., Dharwad",
      nameRequired: "Name is required",
      emailRequired: "Email is required",
      phoneRequired: "Phone is required",
      regionRequired: "Region is required",
      districtRequired: "District is required",
      passwordRequired: "Password is required",
      passwordMatchError: "Passwords do not match",
      registering: "Registering...",
      registrationFailed: "Registration failed",
      registrationError: "Registration error",

      // Crop Recommendation Form
      enterDetails: "Enter Your Farm Details",
      selectSoil: "Select soil type",
      selectRainfall: "Select rainfall range",
      temperature: "Temperature (°C)",
      rainfall: "Expected Rainfall (mm)",
      recommendedCrops: "Recommended Crops",
      bestSeason: "Best Season",
      waterRequirements: "Water Requirements",
      harvestDays: "Days to Harvest",
      profitMargin: "Profit Margin",

      // Admin Dashboard
      adminDashboard: "Admin Dashboard",
      logoutBtn: "Logout",
      totalCrops: "Total Crops",
      totalStores: "Total Stores",
      seedsStat: "Seeds",
      manageContent: "Manage Content",
      addCrop: "Add Crop",
      addSeed: "Add Seed",
      addStore: "Add Store",

      // User Management
      userName: "User Name",
      userEmail: "User Email",
      userStatus: "User Status",
      joinDate: "Join Date",
      lastActive: "Last Active",
      userRole: "User Role",
      farmer: "Farmer",
      active: "Active",
      inactive: "Inactive",
      blocked: "Blocked",

      // Profile Page
      profileDetails: "Profile Details",
      farmLocation: "Farm Location",
      farmSize: "Farm Size",
      primaryCrop: "Primary Crop",
      soilInfo: "Soil Information",
      contactInfo: "Contact Information",
      location: "Location",
      state: "State",
      city: "City",
      notSet: "Not Set",
      na: "N/A",

      // About Page
      ourMission: "Our Mission",
      missionStatement: "We aim to help Karnataka farmers make informed decisions about crop cultivation by providing accurate recommendations based on soil conditions, weather patterns, and market trends.",
      howItWorks: "How It Works",
      soilAnalysisTitle: "Soil Analysis",
      soilAnalysisDesc: "Get recommendations based on your soil type and nutrients",
      weatherDataTitle: "Weather Data",
      weatherDataDesc: "Consider local weather patterns for optimal planting",
      marketTrendsTitle: "Market Trends",
      marketTrendsDesc: "Stay updated with current market demands and prices",

      // Crop Details
      soilTypeInfo: "Soil Type",
      harvestSeason: "Harvest Season",
      waterNeed: "Water Need",
      fertilizer: "Fertilizer",
      pestControl: "Pest Control",
      diseasePrevention: "Disease Prevention",
      yieldPotential: "Yield Potential",
      marketPrice: "Market Price",
      transportationCost: "Transportation Cost",
      storageInfo: "Storage Information",
      processingRequired: "Processing Required",

      // Seed Details
      seedBrand: "Seed Brand",
      seedType: "Seed Type",
      purityLevel: "Purity Level",
      viability: "Viability",
      packSize: "Pack Size",
      expiryDate: "Expiry Date",
      stockAvailable: "Stock Available",
      supplierInfo: "Supplier Information",
      minimumOrder: "Minimum Order",
      deliveryTime: "Delivery Time",

      // Store Details
      storeName: "Store Name",
      storeAddress: "Store Address",
      storePhone: "Store Phone",
      storeEmail: "Store Email",
      storeHours: "Store Hours",
      openingTime: "Opening Time",
      closingTime: "Closing Time",
      productsAvailable: "Products Available",
      deliveryAvailable: "Delivery Available",
      onlineOrdering: "Online Ordering",

      // Messages & Alerts
      failedLoadRecommendations: "Failed to get recommendations. Please try again.",
      tryAgain: "Try Again",
      loading: "Loading...",
      loadingData: "Loading data...",
      dataLoading: "Please wait, data is loading...",

      // Form Fields
      submit: "Submit",
      submitForm: "Submit Form",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      update: "Update",
      search: "Search",
      filter: "Filter",
      error: "Error",
      success: "Success",
      warning: "Warning",
      info: "Info",
      close: "Close",
      confirm: "Confirm",
      apply: "Apply",
      reset: "Reset",
      clear: "Clear",

      // Headers & Titles
      welcomeBack: "Welcome Back!",
      myProfile: "My Profile",
      help: "Help",
      faq: "FAQ",
      contactUs: "Contact Us",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",

      // Soil Types
      redSoil: "Red Soil",
      blackSoil: "Black Soil",
      alluvialSoil: "Alluvial Soil",
      lateriteSoil: "Laterite Soil",
      sandySoil: "Sandy Soil",
      claySoil: "Clay Soil",

      // Rainfall Ranges
      rainfallLow: "< 300 mm (Low)",
      rainfallMedium: "300 - 600 mm (Medium)",
      rainfallMediumHigh: "600 - 900 mm (Medium-High)",
      rainfallHigh: "900 - 1200 mm (High)",
      rainfallVeryHigh: "1200 - 1500 mm (Very High)",
      rainfallExcessive: "> 1500 mm (Excessive)",

      // Store Types
      kssclDepot: "KSSCL Depot",
      krishiVikasKendra: "Krishi Vikas Kendra",
      privateDealer: "Private Dealer",
      cooperativeSociety: "Cooperative Society",

      // Admin Management
      cropManagement: "Crop Management",
      manageCropDesc: "Add, edit, and delete crop data",
      existingCrops: "Existing Crops",
      showLess: "Show less",
      showMore: "Show more",
      days: "days",
      cropNameLabel: "Crop Name",
      selectSeason: "Select Season",
      selectWaterNeeds: "Select Water Needs",
      suitableDistricts: "Suitable Districts",
      fertilizersPlaceholder: "e.g., Urea, DAP, NPK",
      imageURL: "Image URL",
      cropDescription: "Description",
      processing: "Processing...",
      updateCrop: "Update Crop",
      addCropBtn: "Add Crop",
      cropAddedSuccess: "Crop added successfully!",
      cropUpdateSuccess: "Crop updated successfully!",
      cropDeleteSuccess: "Crop deleted successfully!",
      confirmDeleteCrop: "Are you sure you want to delete this crop?",
      notAuthenticated: "Not authenticated",
      loginAsAdminMsg: "Please login as admin to view and manage content.",
      goToAdminLogin: "Go to Admin Login",
      seedManagement: "Seed Management",
      manageSeedDesc: "Add, view and remove seed brands",
      existingSeeds: "Existing Seed Brands",
      seedNameLabel: "Seed Name (Variety)",
      pricePerKg: "Price per kg (₹)",
      germinationRatePercent: "Germination Rate (%)",
      ratingStars: "Rating (Stars 0-5)",
      saving: "Saving...",
      updateSeed: "Update Seed",
      addSeedBrand: "Add Seed Brand",
      seedAddedSuccess: "Seed added successfully!",
      seedUpdateSuccess: "Seed updated successfully!",
      seedDeleteSuccess: "Seed deleted successfully!",
      confirmDeleteSeed: "Delete this seed brand?",
      errorSavingSeed: "Error saving seed",
      storeManagement: "Store Management",
      manageStoreDesc: "Manage agricultural stores and suppliers",
      existingStores: "Existing Stores",
      ownerName: "Owner Name",
      contactNumber: "Contact Number",
      latitude: "Latitude",
      longitude: "Longitude",
      productsAvailableLabel: "Products Available",
      updateStore: "Update Store",
      addStoreBtn: "Add Store",
      storeAddedSuccess: "Store added successfully!",
      storeUpdateSuccess: "Store updated successfully!",
      storeDeleteSuccess: "Store deleted successfully!",
      confirmDeleteStore: "Are you sure you want to delete this store?",
      errorAddingStore: "Error adding store",
      errorUpdatingStore: "Error updating store",
      errorDeletingStore: "Error deleting store",

      // Districts
      dist_Bagalkot: "Bagalkot",
      dist_Ballari: "Ballari",
      dist_Belagavi: "Belagavi",
      dist_Bengaluru_Rural: "Bengaluru Rural",
      dist_Bengaluru_Urban: "Bengaluru Urban",
      dist_Bidar: "Bidar",
      dist_Chamarajanagar: "Chamarajanagar",
      dist_Chikkaballapura: "Chikkaballapura",
      dist_Chikkamagaluru: "Chikkamagaluru",
      dist_Chitradurga: "Chitradurga",
      dist_Dakshina_Kannada: "Dakshina Kannada",
      dist_Davanagere: "Davanagere",
      dist_Dharwad: "Dharwad",
      dist_Gadag: "Gadag",
      dist_Hassan: "Hassan",
      dist_Haveri: "Haveri",
      dist_Kalaburagi: "Kalaburagi",
      dist_Kodagu: "Kodagu",
      dist_Kolar: "Kolar",
      dist_Koppal: "Koppal",
      dist_Mandya: "Mandya",
      dist_Mysuru: "Mysuru",
      dist_Raichur: "Raichur",
      dist_Ramanagara: "Ramanagara",
      dist_Shivamogga: "Shivamogga",
      dist_Tumakuru: "Tumakuru",
      dist_Udupi: "Udupi",
      dist_Uttara_Kannada: "Uttara Kannada",
      dist_Vijayapura: "Vijayapura",
      dist_Yadgir: "Yadgir",
    },
    kn: {
      // Navigation
      home: "ಮುಖಪುಟ",
      about: "ನಿಮ್ಮ ಬಗ್ಗೆ",
      profile: "ಪ್ರೊಫೈಲ್",
      admin: "ನಿರ್ವಾಹಕ",
      login: "ಲಾಗಿನ್",
      register: "ನೋಂದಣಿ",
      logout: "ಲಾಗ್ ಔಟ್",
      learnMore: "ಹೆಚ್ಚು ತಿಳಿದುಕೊಳ್ಳಿ",

      // Hero Section
      heroTitle: "ಕರ್ನಾಟಕಕ್ಕೆ ಸ್ಮಾರ್ಟ ಕೃಷಿ ಪರಿಹಾರ",
      heroSubtitle: "ವ್ಯಕ್ತಿಗತ ಫಸಲು ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ, ಗುಣಮಾನದ ಬೀಜಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ನಿಮ್ಮ ಸಮೀಪವಿದ್ದ ಕೃಷಿ ಮಳಿಗೆಯನ್ನು ಸ್ಥಾನೀಯಗೊಳಿಸಿ",
      getStarted: "ಪ್ರಾರಂಭಿಸಿ",
      smartFarmingTechnology: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ",
      cropVarieties: "ಬೆಳೆ ಪ್ರಭೇದಗಳು",
      storesListed: "ಪಟ್ಟಿ ಮಾಡಲಾದ ಅಂಗಡಿಗಳು",
      regionsCovered: "ಆವರಿಸಿರುವ ಪ್ರದೇಶಗಳು",

      // Features
      features: "ನಮ್ಮ ವೇದಿಕೆಯನ್ನು ಏಕೆ ಆಯ್ಕೆ ಮಾಡಿ?",
      feature1Title: "ಫಸಲು ಶಿಫಾರಸು",
      feature1Desc: "ಮಣ್ಣಿನ ಪ್ರಕಾರ, ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿ ಮತ್ತು ಸ್ಥಳವನ್ನು ಆಧಾರವಾಗಿಟ್ಟುಕೊಂಡು ವ್ಯಕ್ತಿಗತ ಫಸಲು ಸಲಹೆ ಪಡೆಯಿರಿ",
      feature2Title: "ಬೀಜ ಮಾಹಿತಿ",
      feature2Desc: "ವಿವಿಧ ಬೀಜ ಪ್ರಭೇದ ಮತ್ತು ಅವುಗಳ ಗುಣಲಕ್ಷಣಗಳ ಬಗ್ಗೆ ವಿವರವಾದ ಮಾಹಿತಿ ಪಡೆಯುವಿರಿ",
      feature3Title: "ಮಳಿಗೆ ಸ್ಥಾನೀಯತೆ",
      feature3Desc: "ಹತ್ತಿರದ ಕೃಷಿ ಮಳಿಗೆಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ನಿರ್ದೇಶನ ಪಡೆಯುವಿರಿ",
      feature4Title: "ಇಳುವರಿ ವಿಶ್ಲೇಷಣೆ",
      feature4Desc: "ನಿಮ್ಮ ಫಸಲು ಇಳುವರಿಯನ್ನು ಕಾಲಿನೊಂದಿಗೆ ಟ್ರ್যಾಕ್ ಮಾಡಿ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ ಮಾಡಿ",
      whyChooseTitle: "ನಮ್ಮ ವೇದಿಕೆಯನ್ನು ಏಕೆ ಆಯ್ಕೆ ಮಾಡಿ?",
      whyChooseSubtitle: "ಉತ್ತಮ ಬೆಳೆ ನಿರ್ವಹಣೆಗಾಗಿ ತಂತ್ರಜ್ಞಾನದೊಂದಿಗೆ ರೈತರನ್ನು ಸಬಲಗೊಳಿಸುವುದು",
      smartRecommendationsTitle: "ಸ್ಮಾರ್ಟ್ ಶಿಫಾರಸುಗಳು",
      smartRecommendationsDesc: "ಮಣ್ಣು, ಹವಾಮಾನ ಮತ್ತು ಪ್ರಾದೇಶಿಕ ಡೇಟಾವನ್ನು ಆಧರಿಸಿದ AI-ಚಾಲಿತ ಸಲಹೆಗಳು.",
      storeLocatorTitle: "ಅಂಗಡಿ ಪತ್ತೆದಾರ",
      storeLocatorDesc: "ಪರಿಶೀಲಿಸಿದ ವಿಮರ್ಶೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಹತ್ತಿರವಿರುವ ವಿಶ್ವಾಸಾರ್ಹ ಕೃಷಿ ಅಂಗಡಿಗಳನ್ನು ಹುಡುಕಿ.",
      maximizeYieldTitle: "ಇಳುವರಿಯನ್ನು ಹೆಚ್ಚಿಸಿ",
      maximizeYieldDesc: "ಉತ್ಪಾದಕತೆ ಮತ್ತು ಲಾಭವನ್ನು ಹೆಚ್ಚಿಸಲು ಬೆಳೆ ಆಯ್ಕೆಯನ್ನು ಅತ್ಯುತ್ತಮಗೊಳಿಸಿ.",
      trustedDataTitle: "ವಿಶ್ವಾಸಾರ್ಹ ಡೇಟಾ",
      trustedDataDesc: "ಕೃಷಿ ಸಂಶೋಧನೆ ಮತ್ತು ನೈಜ ರೈತರ ಅನುಭವಗಳಿಂದ ಬೆಂಬಲಿತವಾಗಿದೆ.",

      // Quick Actions
      quickActions: "ಈಗ ಪ್ರಾರಂಭಿಸಿ",
      action1Title: "ಫಸಲು ಶಿಫಾರಸು ಪಡೆಯಿರಿ",
      action1Desc: "ನಿಮ್ಮ ಜಮೀನಿಗೆ ಉತ್ತಮ ಫಸಲುಗಳನ್ನು ಹುಡುಕಿ",
      action2Title: "ಬೀಜಗಳನ್ನು ಹುಡುಕಿ",
      action2Desc: "ಸೂಕ್ತ ಬೀಜ ಪ್ರಭೇದಗಳನ್ನು ಆವಿಷ್ಕರಿಸಿ",
      action3Title: "ಮಳಿಗೆಯನ್ನು ಸ್ಥಾನೀಯಗೊಳಿಸಿ",
      action3Desc: "ನಿಮ್ಮ ಸಮೀಪವಿದ್ದ ಕೃಷಿ ಮಳಿಗೆಗಳನ್ನು ಹುಡುಕಿ",
      readyToStart: "ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
      joinFarmers: "ಪ್ರತಿದಿನ ಚುರುಕಾದ ಬೆಳೆ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುವ ಸಾವಿರಾರು ರೈತರೊಂದಿಗೆ ಸೇರಿ.",
      getRecommendationBtn: "ನಿಮ್ಮ ಶಿಫಾರಸು ಪಡೆಯಿರಿ →",
      footerRights: "ಬೆಳೆ ಶಿಫಾರಸು ವ್ಯವಸ್ಥೆ — ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ",

      // Crop Recommendation
      cropRecommendation: "ಫಸಲು ಶಿಫಾರಸು",
      recommendationDesc: "ನಿಮ್ಮ ಜಮೀನಿನ ಸ್ಥಳ ಮತ್ತು ಪರಿಸ್ಥಿತಿಗಳ ಆಧಾರದ ಮೇಲೆ ವ್ಯಕ್ತಿಗತ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ",
      cropTab: "ಫಸಲು ಶಿಫಾರಸು",
      seedTab: "ಬೀಜ ಹುಡುಕಾಟ",
      storeTab: "ಮಳಿಗೆ ಸ್ಥಾನೀಯತೆ",
      authRequired: "ಪ್ರಮಾಣೀಕರಣ ಬೇಕಾಗಿದೆ",
      loginMessage: "ಫಸಲು ಶಿಫಾರಸುಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ದಯವಿಟ್ಟು ನೋಂದಣಿ ಅಥವಾ ಲಾಗಿನ್ ಮಾಡಿ",
      enterTemp: "ತಾಪಮಾನವನ್ನು ನಮೂದಿಸಿ",
      match: "ಹೊಂದಿಕೆ",
      season: "ಋತು",
      duration: "ಅವಧಿ",
      waterNeeds: "ನೀರಿನ ಅಗತ್ಯಗಳು",
      fertilizers: "ಗೊಬ್ಬರಗಳು",
      expectedYield: "ನಿರೀಕ್ಷಿತ ಇಳುವರಿ",
      noDataFound: "ಡೇಟಾ ಕಂಡುಬಂದಿಲ್ಲ",

      // Seed Recommendation
      seedRecommendation: "ಬೀಜ ಶಿಫಾರಸು",
      cropName: "ಫಸಲಿನ ಹೆಸರು",
      enterCropName: "ಫಸಲಿನ ಹೆಸರನ್ನು ನಮೂದಿಸಿ (ಉದಾ, ಬೇಸವಳೆ, ಪಟ್ಟ, ನೆರೆತೇಪ್ಪಾಲಿ)",
      findSeeds: "ಬೀಜಗಳನ್ನು ಹುಡುಕಿ",
      seedVarieties: "ಬೀಜ ಪ್ರಭೇದಗಳು",
      type: "ಪ್ರಕಾರ",
      brand: "ಬ್ರ್ಯಾಂಡ್",
      price: "ಬೆಲೆ",
      germination: "ಬೀಜ ಅಂಕುರಣ ದರ",
      features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
      contactSupplier: "ಪೂರೈಕೆದಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ",
      quickSelect: "ತ್ವರಿತ ಆಯ್ಕೆ:",
      for: "ಗೆ",
      enterCropToFind: "ಶಿಫಾರಸು ಮಾಡಲಾದ ಬೀಜ ಪ್ರಭೇದಗಳನ್ನು ಹುಡುಕಲು ಬೆಳೆಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.",

      // Store Recommendation
      storeRecommendation: "ಮಳಿಗೆ ಸ್ಥಾನೀಯತೆ",
      district: "ಜಿಲ್ಲೆ",
      selectDistrict: "ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
      storeType: "ಮಳಿಗೆ ಪ್ರಕಾರ",
      selectType: "ಎಲ್ಲಾ ಪ್ರಕಾರಗಳು",
      findStores: "ಮಳಿಗೆಗಳನ್ನು ಹುಡುಕಿ",
      noStoresFound: "ನಿಮ್ಮ ಆಯ್ಕೆಗೆ ಮಳಿಗೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
      address: "ವಿಳಾಸ",
      contact: "ಸಂಪರ್ಕ",
      allStores: "ಎಲ್ಲಾ ಅಂಗಡಿಗಳು",
      nearbyStores: "ಹತ್ತಿರದ ಅಂಗಡಿಗಳು",
      in: "ನಲ್ಲಿ",
      govtApproved: "ಸರ್ಕಾರ ಅನುಮೋದಿತ",
      timing: "ಸಮಯ",
      products: "ಉತ್ಪನ್ನಗಳು",
      availableSeeds: "ಲಭ್ಯವಿರುವ ಬೀಜಗಳು:",
      reviews: "ವಿಮರ್ಶೆಗಳು",
      noStoresInDistrict: "{district} ನಲ್ಲಿ ಯಾವುದೇ ಅಂಗಡಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಬೇರೆ ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ಪ್ರಯತ್ನಿಸಿ.",
      selectDistrictPrompt: "ಹತ್ತಿರದ ಅಂಗಡಿಗಳನ್ನು ಹುಡುಕಲು ದಯವಿಟ್ಟು ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
      getDirections: "ನಿರ್ದೇಶನಗಳನ್ನು ಪಡೆಯಿರಿ",
      callStore: "ಅಂಗಡಿಗೆ ಕರೆ ಮಾಡಿ",

      // Profile
      personalInfo: "ವ್ಯಕ್ತಿಗತ ಮಾಹಿತಿ",
      name: "ಹೆಸರು",
      email: "ಇಮೇಲ್",
      phone: "ಫೋನ್",
      soilType: "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
      recommendationHistory: "ಶಿಫಾರಸು ಇತಿಹಾಸ",
      history: "ಇತಿಹಾಸ",
      details: "ವಿವರಣೆ",
      settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",

      // Admin
      dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
      totalUsers: "ಒಟ್ಟು ಬಳಕೆದಾರರು",
      recommendations: "ಶಿಫಾರಸುಗಳು",
      crops: "ಸಕ್ರಿಯ ಫಸಲುಗಳು",
      stores: "ನೋಂದಾಯಿತ ಮಳಿಗೆಗಳು",
      manageUsers: "ಬಳಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ",
      manageCrops: "ಫಸಲುಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
      manageStores: "ಮಳಿಗೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
      users: "ಬಳಕೆದಾರರು",
      adminPanel: "ನಿರ್ವಾಹಕ ಫಲಕ",
      defaultCredentials: "ಡೀಫಾಲ್ಟ್ ರುಜುವಾತುಗಳು: admin@gmail.com / admin123",
      registeredUsers: "ನೋಂದಾಯಿತ ಬಳಕೆದಾರರು",
      role: "ಪಾತ್ರ",
      actions: "ಕ್ರಿಯೆಗಳು",
      confirmDeleteUser: "ಈ ಬಳಕೆದಾರರನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
      addNewContent: "ಹೊಸ ವಿಷಯವನ್ನು ಸೇರಿಸಿ",
      selectContentToAdd: "ವ್ಯವಸ್ಥೆಗೆ ನೀವು ಏನನ್ನು ಸೇರಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ",
      addCropDesc: "ಅವಶ್ಯಕತೆಗಳೊಂದಿಗೆ ಹೊಸ ಫಸಲು ಡೇಟಾವನ್ನು ಸೇರಿಸಿ",
      addStoreDesc: "ಸಂಪರ್ಕ ಮಾಹಿತಿಯೊಂದಿಗೆ ಕೃಷಿ ಮಳಿಗೆಗಳನ್ನು ಸೇರಿಸಿ",
      addSeedDesc: "ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಅಂಕಗಳೊಂದಿಗೆ ಬೀಜ ಬ್ರ್ಯಾಂಡ್‌ಗಳನ್ನು ಸೇರಿಸಿ",
      backToAll: "ಎಲ್ಲದಕ್ಕೂ ಹಿಂತಿರುಗಿ",

      // Auth
      fullName: "ಪೂರ್ಣ ಹೆಸರು",
      password: "ಪಾಸ್ವರ್ಡ್",
      confirmPassword: "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
      region: "ಪ್ರದೇಶ",
      alreadyAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?",
      noAccount: "ಖಾತೆ ಹೊಂದಿಲ್ಲವೇ?",
      registerHere: "ಇಲ್ಲಿ ನೋಂದಣಿ ಮಾಡಿ",
      loginHere: "ಇಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ",
      userLogin: "ಬಳಕೆದಾರ ಲಾಗಿನ್",
      adminLogin: "ನಿರ್ವಾಹಕ ಲಾಗಿನ್",
      enterEmail: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.",
      passwordLengthError: "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು.",
      loginFailed: "ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ",
      loginError: "ಲಾಗಿನ್ ದೋಷ",
      registerPrompt: "ಖಾತೆ ಇಲ್ಲವೇ?",
      loginPrompt: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?",
      phonePlaceholder: "10-ಅಂಕಿಯ ಫೋನ್ ಸಂಖ್ಯೆ",
      regionPlaceholder: "ಉದಾ, ಉತ್ತರ ಕರ್ನಾಟಕ",
      districtPlaceholder: "ಉದಾ, ಧಾರವಾಡ",
      nameRequired: "ಹೆಸರು ಅಗತ್ಯವಿದೆ",
      emailRequired: "ಇಮೇಲ್ ಅಗತ್ಯವಿದೆ",
      phoneRequired: "ಫೋನ್ ಅಗತ್ಯವಿದೆ",
      regionRequired: "ಪ್ರದೇಶ ಅಗತ್ಯವಿದೆ",
      districtRequired: "ಜಿಲ್ಲೆ ಅಗತ್ಯವಿದೆ",
      passwordRequired: "ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯವಿದೆ",
      passwordMatchError: "ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ",
      registering: "ನೋಂದಾಯಿಸಲಾಗುತ್ತಿದೆ...",
      registrationFailed: "ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ",
      registrationError: "ನೋಂದಣಿ ದೋಷ",

      // Crop Recommendation Form
      enterDetails: "ನಿಮ್ಮ ಜಮೀನಿನ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
      selectSoil: "ಮಣ್ಣಿನ ಪ್ರಕಾರ ಆಯ್ಕೆ ಮಾಡಿ",
      selectRainfall: "ವರ್ಷಾಂಶ ಶ್ರೇಣಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
      temperature: "ತಾಪಮಾನ (°C)",
      rainfall: "ನಿರೀಕ್ಷಿತ ವರ್ಷಾಕಾಲ (ಮಿಮೀ)",
      recommendedCrops: "ಶಿಫಾರಸಿತ ಫಸಲುಗಳು",
      bestSeason: "ಅತ್ಯುತ್ತಮ ಋತು",
      waterRequirements: "ನೀರಿನ ಅವಶ್ಯಕತೆ",
      harvestDays: "ಸುಗ್ರಹಿಕೆ ಗಳಿಕೆ ಗಳಿಗೆ ದಿನಗಳು",
      profitMargin: "ಲಾಭ ಅಂತರ",

      // Admin Dashboard
      adminDashboard: "ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
      logoutBtn: "ಲಾಗ್ ಔಟ್",
      totalCrops: "ಒಟ್ಟು ಫಸಲುಗಳು",
      totalStores: "ಒಟ್ಟು ಮಳಿಗೆಗಳು",
      seedsStat: "ಬೀಜಗಳು",
      manageContent: "ವಿಷಯವನ್ನು ನಿರ್ವಹಿಸಿ",
      addCrop: "ಫಸಲನ್ನು ಸೇರಿಸಿ",
      addSeed: "ಬೀಜವನ್ನು ಸೇರಿಸಿ",
      addStore: "ಮಳಿಗೆಯನ್ನು ಸೇರಿಸಿ",

      // User Management
      userName: "ಬಳಕೆದಾರರ ಹೆಸರು",
      userEmail: "ಬಳಕೆದಾರರ ಇಮೇಲ್",
      userStatus: "ಬಳಕೆದಾರರ ಸ್ಥಿತಿ",
      joinDate: "ಸೇರುವ ದಿನಾಂಕ",
      lastActive: "ಕೊನೆಯ ಸಕ್ರಿಯ",
      userRole: "ಬಳಕೆದಾರರ ಪಾತ್ರ",
      farmer: "ರೈತ",
      active: "ಸಕ್ರಿಯ",
      inactive: "ನಿಷ್ಕ್ರಿಯ",
      blocked: "ನಿರ್ಬಂಧಿತ",

      // Profile Page
      profileDetails: "ಪ್ರೊಫೈಲ್ ವಿವರಣೆ",
      farmLocation: "ಜಮೀನಿನ ಸ್ಥಳ",
      farmSize: "ಜಮೀನಿನ ಗಾತ್ರ",
      primaryCrop: "ಪ್ರಧಾನ ಫಸಲು",
      soilInfo: "ಮಣ್ಣಿನ ಮಾಹಿತಿ",
      contactInfo: "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
      location: "ಸ್ಥಳ",
      state: "ರಾಜ್ಯ",
      city: "ನಗರ",
      notSet: "ಹೊಂದಿಸಲಾಗಿಲ್ಲ",
      na: "ಅನ್ವಯಿಸುವುದಿಲ್ಲ",

      // About Page
      ourMission: "ನಮ್ಮ ಧ್ಯೇಯ",
      missionStatement: "ಮಣ್ಣಿನ ಪರಿಸ್ಥಿತಿಗಳು, ಹವಾಮಾನ ಮಾದರಿಗಳು ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳ ಆಧಾರದ ಮೇಲೆ ನಿಖರವಾದ ಶಿಫಾರಸುಗಳನ್ನು ಒದಗಿಸುವ ಮೂಲಕ ಬೆಳೆ ಕೃಷಿಯ ಬಗ್ಗೆ ತಿಳುವಳಿಕೆಯುಳ್ಳ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ಕರ್ನಾಟಕದ ರೈತರಿಗೆ ಸಹಾಯ ಮಾಡುವುದು ನಮ್ಮ ಗುರಿಯಾಗಿದೆ.",
      howItWorks: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
      soilAnalysisTitle: "ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣೆ",
      soilAnalysisDesc: "ನಿಮ್ಮ ಮಣ್ಣಿನ ಪ್ರಕಾರ ಮತ್ತು ಪೋಷಕಾಂಶಗಳ ಆಧಾರದ ಮೇಲೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ",
      weatherDataTitle: "ಹವಾಮಾನ ಡೇಟಾ",
      weatherDataDesc: "ಅತ್ಯುತ್ತಮ ನಾಟಿಗಾಗಿ ಸ್ಥಳೀಯ ಹವಾಮಾನ ಮಾದರಿಗಳನ್ನು ಪರಿಗಣಿಸಿ",
      marketTrendsTitle: "ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳು",
      marketTrendsDesc: "ಪ್ರಸ್ತುತ ಮಾರುಕಟ್ಟೆ ಬೇಡಿಕೆಗಳು ಮತ್ತು ಬೆಲೆಗಳೊಂದಿಗೆ ನವೀಕೃತವಾಗಿರಿ",

      // Crop Details
      soilTypeInfo: "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
      harvestSeason: "ಸುಗ್ರಹಿಕೆ ಋತು",
      waterNeed: "ನೀರಿನ ಅವಶ್ಯಕತೆ",
      fertilizer: "ಗೊಬರು",
      pestControl: "ಕೀಟ ನಿಯಂತ್ರಣ",
      diseasePrevention: "ರೋಗ ತಡೆ",
      yieldPotential: "ಇಳುವರಿ ಸಾಮರ್ಥ್ಯ",
      marketPrice: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ",
      transportationCost: "ಸರಿಸಾಮಗ್ರಿ ವೆಚ್ಚ",
      storageInfo: "ಸಂಗ್ರಹಣ ಮಾಹಿತಿ",
      processingRequired: "ಸಂಸ್ಕರಣೆ ಅವಶ್ಯಕ",

      // Seed Details
      seedBrand: "ಬೀಜ ಬ್ರ್ಯಾಂಡ್",
      seedType: "ಬೀಜ ಪ್ರಕಾರ",
      purityLevel: "ಶುದ್ಧತೆ ಮಟ್ಟ",
      viability: "ಆಜೀವನತ್ವ",
      packSize: "ಪ್ಯಾಕ್ ಗಾತ್ರ",
      expiryDate: "ಅವಧಿ ಮುಗಿಯುವ ದಿನಾಂಕ",
      stockAvailable: "ಸ್ಟಾಕ್ ಲಭ್ಯತೆ",
      supplierInfo: "ಪೂರೈಕೆದಾರರ ಮಾಹಿತಿ",
      minimumOrder: "ಕನಿಷ್ಠ ಆದೇಶ",
      deliveryTime: "ವಿತರಣ ಸಮಯ",

      // Store Details
      storeName: "ಮಳಿಗೆ ಹೆಸರು",
      storeAddress: "ಮಳಿಗೆ ವಿಳಾಸ",
      storePhone: "ಮಳಿಗೆ ಫೋನ್",
      storeEmail: "ಮಳಿಗೆ ಇಮೇಲ್",
      storeHours: "ಮಳಿಗೆ ಗಂಟೆಗಳು",
      openingTime: "ಪ್ರಾರಂಭ ಸಮಯ",
      closingTime: "ಸಮಾಪ್ತ ಸಮಯ",
      productsAvailable: "ಲಭ್ಯ ಉತ್ಪನ್ನಗಳು",
      deliveryAvailable: "ವಿತರಣ ಲಭ್ಯತೆ",
      onlineOrdering: "ಆನ್ಲೈನ್ ಆದೇಶ",

      // Messages & Alerts
      failedLoadRecommendations: "ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ವಿಫಲ. ಮತ್ತೆ ಪ್ರಯತ್ನ ಮಾಡಿ.",
      tryAgain: "ಮತ್ತೆ ಪ್ರಯತ್ನ ಮಾಡಿ",
      loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
      loadingData: "ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
      dataLoading: "ದಯವಿಟ್ಟು ಹೋಕುಳಿ ಬಿಡಿ, ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",

      // Form Fields
      submit: "ಸಲ್ಲಿಸಿ",
      submitForm: "ಫಾರ್ಮ್ ಸಲ್ಲಿಸಿ",
      cancel: "ರದ್ದು ಮಾಡಿ",
      save: "ಉಳಿಸಿ",
      delete: "ಅಳಿಸಿ",
      edit: "ಸಂಪಾದನೆ",
      update: "ನವೀಕರಣ",
      search: "ಹುಡುಕಾಟ",
      filter: "ಸೋಸಣೆ",
      error: "ದೋಷ",
      success: "ಯಶಸ್ಸು",
      warning: "ಎಚ್ಚರಿಕೆ",
      info: "ಮಾಹಿತಿ",
      close: "ಮುಚ್ಚಿ",
      confirm: "ದೃಢೀಕರಿಸಿ",
      apply: "ಅನ್ವಯಿಸಿ",
      reset: "ಮರುಹೊಂದಿಸಿ",
      clear: "ಸ್ಪಷ್ಟ",

      // Headers & Titles
      welcomeBack: "ಸ್ವಾಗತ!",
      myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
      help: "ಸಹಾಯತೆ",
      faq: "ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು",
      contactUs: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
      privacy: "ಗೌಪ್ಯತೆ ನೀತಿ",
      terms: "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",

      // Soil Types
      redSoil: "ಕೆಂಪು ಮಣ್ಣು",
      blackSoil: "ಕಪ್ಪು ಮಣ್ಣು",
      alluvialSoil: "ಮೆಕ್ಕಲು ಮಣ್ಣು",
      lateriteSoil: "ಲ್ಯಾಟರೈಟ್ ಮಣ್ಣು",
      sandySoil: "ಮರಳು ಮಣ್ಣು",
      claySoil: "ಜೇಡಿ ಮಣ್ಣು",

      // Rainfall Ranges
      rainfallLow: "< 300 ಮಿಮೀ (ಕಡಿಮೆ)",
      rainfallMedium: "300 - 600 ಮಿಮೀ (ಮಧ್ಯಮ)",
      rainfallMediumHigh: "600 - 900 ಮಿಮೀ (ಮಧ್ಯಮ-ಹೆಚ್ಚು)",
      rainfallHigh: "900 - 1200 ಮಿಮೀ (ಹೆಚ್ಚು)",
      rainfallVeryHigh: "1200 - 1500 ಮಿಮೀ (ತುಂಬಾ ಹೆಚ್ಚು)",
      rainfallExcessive: "> 1500 ಮಿಮೀ (ವಿಪರೀತ)",

      // Store Types
      kssclDepot: "ಕೆಎಸ್‌ಎಸ್‌ಸಿಎಲ್ ಡಿಪೋ",
      krishiVikasKendra: "ಕೃಷಿ ವಿಕಾಸ ಕೇಂದ್ರ",
      privateDealer: "ಖಾಸಗಿ ವ್ಯಾಪಾರಿ",
      cooperativeSociety: "ಸಹಕಾರಿ ಸಂಘ",

      // Admin Management
      cropManagement: "ಫಸಲು ನಿರ್ವಹಣೆ",
      manageCropDesc: "ಫಸಲು ಡೇಟಾವನ್ನು ಸೇರಿಸಿ, ಸಂಪಾದಿಸಿ ಮತ್ತು ಅಳಿಸಿ",
      existingCrops: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಫಸಲುಗಳು",
      showLess: "ಕಡಿಮೆ ತೋರಿಸಿ",
      showMore: "ಹೆಚ್ಚು ತೋರಿಸಿ",
      days: "ದಿನಗಳು",
      cropNameLabel: "ಫಸಲಿನ ಹೆಸರು",
      selectSeason: "ಋತುವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
      selectWaterNeeds: "ನೀರಿನ ಅಗತ್ಯಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
      suitableDistricts: "ಸೂಕ್ತ ಜಿಲ್ಲೆಗಳು",
      fertilizersPlaceholder: "ಉದಾ, ಯೂರಿಯಾ, ಡಿಎಪಿ, ಎನ್‌ಪಿಕೆ",
      imageURL: "ಚಿತ್ರದ URL",
      cropDescription: "ವಿವರಣೆ",
      processing: "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
      updateCrop: "ಫಸಲನ್ನು ನವೀಕರಿಸಿ",
      addCropBtn: "ಫಸಲನ್ನು ಸೇರಿಸಿ",
      cropAddedSuccess: "ಫಸಲನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ!",
      cropUpdateSuccess: "ಫಸಲನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!",
      cropDeleteSuccess: "ಫಸಲನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ!",
      confirmDeleteCrop: "ಈ ಫಸಲನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
      notAuthenticated: "ಪ್ರಮಾಣೀಕರಿಸಲಾಗಿಲ್ಲ",
      loginAsAdminMsg: "ವಿಷಯವನ್ನು ವೀಕ್ಷಿಸಲು ಮತ್ತು ನಿರ್ವಹಿಸಲು ದಯವಿಟ್ಟು ನಿರ್ವಾಹಕರಾಗಿ ಲಾಗಿನ್ ಮಾಡಿ.",
      goToAdminLogin: "ನಿರ್ವಾಹಕ ಲಾಗಿನ್‌ಗೆ ಹೋಗಿ",
      seedManagement: "ಬೀಜ ನಿರ್ವಹಣೆ",
      manageSeedDesc: "ಬೀಜ ಬ್ರ್ಯಾಂಡ್‌ಗಳನ್ನು ಸೇರಿಸಿ, ವೀಕ್ಷಿಸಿ ಮತ್ತು ತೆಗೆದುಹಾಕಿ",
      existingSeeds: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಬೀಜ ಬ್ರ್ಯಾಂಡ್‌ಗಳು",
      seedNameLabel: "ಬೀಜದ ಹೆಸರು (ವೈವಿಧ್ಯ)",
      pricePerKg: "ಪ್ರತಿ ಕೆಜಿಗೆ ಬೆಲೆ (₹)",
      germinationRatePercent: "ಅಂಕುರಣ ದರ (%)",
      ratingStars: "ರೇಟಿಂಗ್ (ನಕ್ಷತ್ರಗಳು 0-5)",
      saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
      updateSeed: "ಬೀಜವನ್ನು ನವೀಕರಿಸಿ",
      addSeedBrand: "ಬೀಜ ಬ್ರ್ಯಾಂಡ್ ಸೇರಿಸಿ",
      seedAddedSuccess: "ಬೀಜವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ!",
      seedUpdateSuccess: "ಬೀಜವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!",
      seedDeleteSuccess: "ಬೀಜವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ!",
      confirmDeleteSeed: "ಈ ಬೀಜ ಬ್ರ್ಯಾಂಡ್ ಅಳಿಸುವುದೇ?",
      errorSavingSeed: "ಬೀಜವನ್ನು ಉಳಿಸುವಲ್ಲಿ ದೋಷ",
      storeManagement: "ಮಳಿಗೆ ನಿರ್ವಹಣೆ",
      manageStoreDesc: "ಕೃಷಿ ಮಳಿಗೆಗಳು ಮತ್ತು ಪೂರೈಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ",
      existingStores: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಮಳಿಗೆಗಳು",
      ownerName: "ಮಾಲೀಕರ ಹೆಸರು",
      contactNumber: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
      latitude: "ಅಕ್ಷಾಂಶ",
      longitude: "ರೇಖಾಂಶ",
      productsAvailableLabel: "ಲಭ್ಯವಿರುವ ಉತ್ಪನ್ನಗಳು",
      updateStore: "ಮಳಿಗೆಯನ್ನು ನವೀಕರಿಸಿ",
      addStoreBtn: "ಮಳಿಗೆಯನ್ನು ಸೇರಿಸಿ",
      storeAddedSuccess: "ಮಳಿಗೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ!",
      storeUpdateSuccess: "ಮಳಿಗೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!",
      storeDeleteSuccess: "ಮಳಿಗೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ!",
      confirmDeleteStore: "ಈ ಮಳಿಗೆಯನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
      errorAddingStore: "ಮಳಿಗೆಯನ್ನು ಸೇರಿಸುವಲ್ಲಿ ದೋಷ",
      errorUpdatingStore: "ಮಳಿಗೆಯನ್ನು ನವೀಕರಿಸುವಲ್ಲಿ ದೋಷ",
      errorDeletingStore: "ಮಳಿಗೆಯನ್ನು ಅಳಿಸುವಲ್ಲಿ ದೋಷ",

      // Districts
      dist_Bagalkot: "ಬಾಗಲಕೋಟೆ",
      dist_Ballari: "ಬಳ್ಳಾರಿ",
      dist_Belagavi: "ಬೆಳಗಾವಿ",
      dist_Bengaluru_Rural: "ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ",
      dist_Bengaluru_Urban: "ಬೆಂಗಳೂರು ನಗರ",
      dist_Bidar: "ಬೀದರ್",
      dist_Chamarajanagar: "ಚಾಮರಾಜನಗರ",
      dist_Chikkaballapura: "ಚಿಕ್ಕಬಳ್ಳಾಪುರ",
      dist_Chikkamagaluru: "ಚಿಕ್ಕಮಗಳೂರು",
      dist_Chitradurga: "ಚಿತ್ರದುರ್ಗ",
      dist_Dakshina_Kannada: "ದಕ್ಷಿಣ ಕನ್ನಡ",
      dist_Davanagere: "ದಾವಣಗೆರೆ",
      dist_Dharwad: "ಧಾರವಾಡ",
      dist_Gadag: "ಗದಗ",
      dist_Hassan: "ಹಾಸನ",
      dist_Haveri: "ಹಾವೇರಿ",
      dist_Kalaburagi: "ಕಲಬುರಗಿ",
      dist_Kodagu: "ಕೊಡಗು",
      dist_Kolar: "ಕೋಲಾರ",
      dist_Koppal: "ಕೊಪ್ಪಳ",
      dist_Mandya: "ಮಂಡ್ಯ",
      dist_Mysuru: "ಮೈಸೂರು",
      dist_Raichur: "ರಾಯಚೂರು",
      dist_Ramanagara: "ರಾಮನಗರ",
      dist_Shivamogga: "ಶಿವಮೊಗ್ಗ",
      dist_Tumakuru: "ತುಮಕೂರು",
      dist_Udupi: "ಉಡುಪಿ",
      dist_Uttara_Kannada: "ಉತ್ತರ ಕನ್ನಡ",
      dist_Vijayapura: "ವಿಜಯಪುರ",
      dist_Yadgir: "ಯಾದಗಿರಿ",
    },
    hi: {
      // Navigation
      home: "होम",
      about: "परिचय",
      profile: "प्रोफाइल",
      admin: "प्रशासक",
      login: "लॉगिन करें",
      register: "पंजीकरण करें",
      logout: "लॉगआउट",
      learnMore: "अधिक जानें",

      // Hero Section
      heroTitle: "कर्नाटक के लिए स्मार्ट खेती समाधान",
      heroSubtitle: "व्यक्तिगत फसल सिफारिशें प्राप्त करें, गुणवत्ता वाले बीज खोजें और आपके पास कृषि दुकानों का पता लगाएं",
      getStarted: "शुरुआत करें",
      smartFarmingTechnology: "स्मार्ट खेती तकनीक",
      cropVarieties: "फसल की किस्में",
      storesListed: "दुकानें सूचीबद्ध",
      regionsCovered: "कवर किए गए क्षेत्र",

      // Features
      features: "हमारे प्लेटफॉर्म को क्यों चुनें?",
      feature1Title: "फसल सिफारिश",
      feature1Desc: "मिट्टी के प्रकार, मौसम की स्थिति और स्थान के आधार पर व्यक्तिगत फसल सुझाव प्राप्त करें",
      feature2Title: "बीज जानकारी",
      feature2Desc: "विभिन्न बीज किस्मों और उनकी विशेषताओं के बारे में विस्तृत जानकारी प्राप्त करें",
      feature3Title: "दुकान लोकेटर",
      feature3Desc: "पास के कृषि दुकानें खोजें और निर्देश प्राप्त करें",
      feature4Title: "उपज विश्लेषण",
      feature4Desc: "समय के साथ अपनी फसल की पैदावार को ट्रैक और विश्लेषण करें",
      whyChooseTitle: "हमारा मंच क्यों चुनें?",
      whyChooseSubtitle: "बेहतर फसल प्रबंधन के लिए तकनीक के साथ किसानों को सशक्त बनाना",
      smartRecommendationsTitle: "स्मार्ट सिफारिशें",
      smartRecommendationsDesc: "मिट्टी, जलवायु और क्षेत्रीय डेटा के आधार पर एआई-संचालित सुझाव।",
      storeLocatorTitle: "दुकान लोकेटर",
      storeLocatorDesc: "सत्यापित समीक्षाओं के साथ अपने पास विश्वसनीय कृषि दुकानें खोजें।",
      maximizeYieldTitle: "उपज अधिकतम करें",
      maximizeYieldDesc: "उत्पादकता और मुनाफा बढ़ाने के लिए फसल चयन का अनुकूलन करें।",
      trustedDataTitle: "विश्वसनीय डेटा",
      trustedDataDesc: "कृषि अनुसंधान और वास्तविक किसान अनुभवों द्वारा समर्थित।",

      // Quick Actions
      quickActions: "अभी शुरुआत करें",
      action1Title: "फसल सिफारिश प्राप्त करें",
      action1Desc: "अपनी जमीन के लिए सर्वश्रेष्ठ फसलें खोजें",
      action2Title: "बीज खोजें",
      action2Desc: "उपयुक्त बीज किस्में खोजें",
      action3Title: "दुकान स्थानीयकरण करें",
      action3Desc: "आपके पास कृषि दुकानें खोजें",
      readyToStart: "शुरू करने के लिए तैयार हैं?",
      joinFarmers: "हर दिन बेहतर फसल निर्णय लेने वाले हजारों किसानों से जुड़ें।",
      getRecommendationBtn: "अपनी सिफारिश प्राप्त करें →",
      footerRights: "फसल सिफारिश प्रणाली — सर्वाधिकार सुरक्षित",

      // Crop Recommendation
      cropRecommendation: "फसल सिफारिश",
      recommendationDesc: "अपनी जमीन की स्थान और परिस्थितियों के आधार पर व्यक्तिगत सिफारिशें प्राप्त करें",
      cropTab: "फसल सिफारिश",
      seedTab: "बीज फाइंडर",
      storeTab: "दुकान लोकेटर",
      authRequired: "प्रमाणीकरण आवश्यक है",
      loginMessage: "फसल सिफारिशों तक पहुंचने के लिए कृपया पंजीकरण करें या लॉगिन करें",
      enterTemp: "तापमान दर्ज करें",
      match: "मैच",
      season: "मौसम",
      duration: "अवधि",
      waterNeeds: "जल की आवश्यकताएं",
      fertilizers: "उर्वरक",
      expectedYield: "अपेक्षित उपज",
      noDataFound: "कोई डेटा नहीं मिला",

      // Seed Recommendation
      seedRecommendation: "बीज सिफारिश",
      cropName: "फसल का नाम",
      enterCropName: "फसल का नाम दर्ज करें (जैसे, मूंगफली, कपास, चावल)",
      findSeeds: "बीज खोजें",
      seedVarieties: "बीज किस्में",
      type: "प्रकार",
      brand: "ब्रांड",
      price: "कीमत",
      germination: "अंकुरण दर",
      features: "विशेषताएं",
      contactSupplier: "आपूर्तिकर्ता से संपर्क करें",
      quickSelect: "त्वरित चयन:",
      for: "के लिए",
      enterCropToFind: "अनुशंसित बीज किस्मों को खोजने के लिए फसल का नाम दर्ज करें।",

      // Store Recommendation
      storeRecommendation: "दुकान लोकेटर",
      district: "जिला",
      selectDistrict: "जिला चुनें",
      storeType: "दुकान का प्रकार",
      selectType: "सभी प्रकार",
      findStores: "दुकानें खोजें",
      noStoresFound: "आपके चयन के लिए कोई दुकान नहीं मिली",
      address: "पता",
      contact: "संपर्क",
      allStores: "सभी दुकानें",
      nearbyStores: "पास की दुकानें",
      in: "में",
      govtApproved: "सरकार द्वारा अनुमोदित",
      timing: "समय",
      products: "उत्पाद",
      availableSeeds: "उपलब्ध बीज:",
      reviews: "समीक्षाएं",
      noStoresInDistrict: "{district} में कोई दुकान नहीं मिली। एक अलग जिला चुनने का प्रयास करें।",
      selectDistrictPrompt: "पास की दुकानें खोजने के लिए कृपया एक जिला चुनें।",
      getDirections: "दिशा - निर्देश प्राप्त करें",
      callStore: "दुकान को कॉल करें",

      // Profile
      personalInfo: "व्यक्तिगत जानकारी",
      name: "नाम",
      email: "ईमेल",
      phone: "फोन",
      soilType: "मिट्टी का प्रकार",
      recommendationHistory: "सिफारिश का इतिहास",
      history: "इतिहास",
      details: "विवरण",
      settings: "सेटिंग्स",

      // Admin
      dashboard: "डैशबोर्ड",
      totalUsers: "कुल उपयोगकर्ता",
      recommendations: "सिफारिशें",
      crops: "सक्रिय फसलें",
      stores: "पंजीकृत दुकानें",
      manageUsers: "उपयोगकर्ताओं को प्रबंधित करें",
      manageCrops: "फसलों को प्रबंधित करें",
      manageStores: "दुकानों को प्रबंधित करें",
      users: "उपयोगकर्ता",
      adminPanel: "प्रशासक पैनल",
      defaultCredentials: "डिफ़ॉल्ट क्रेडेंशियल्स: admin@gmail.com / admin123",
      registeredUsers: "पंजीकृत उपयोगकर्ता",
      role: "भूमिका",
      actions: "क्रियाएं",
      confirmDeleteUser: "क्या आप वाकई इस उपयोगकर्ता को हटाना चाहते हैं?",
      addNewContent: "नई सामग्री जोड़ें",
      selectContentToAdd: "सिस्टम में आप क्या जोड़ना चाहते हैं, उसका चयन करें",
      addCropDesc: "आवश्यकताओं के साथ नई फसल डेटा जोड़ें",
      addStoreDesc: "संपर्क जानकारी के साथ कृषि दुकानें जोड़ें",
      addSeedDesc: "विश्वसनीयता स्कोर के साथ बीज ब्रांड जोड़ें",
      backToAll: "सभी पर वापस जाएं",

      // Auth
      fullName: "पूरा नाम",
      password: "पासवर्ड",
      confirmPassword: "पासवर्ड की पुष्टि करें",
      region: "क्षेत्र",
      alreadyAccount: "पहले से खाता है?",
      noAccount: "खाता नहीं है?",
      registerHere: "यहां पंजीकरण करें",
      loginHere: "यहां लॉगिन करें",
      userLogin: "उपयोगकर्ता लॉगिन",
      adminLogin: "व्यवस्थापक लॉगिन",
      enterEmail: "कृपया एक मान्य ईमेल पता दर्ज करें।",
      passwordLengthError: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
      loginFailed: "लॉगिन विफल",
      loginError: "लॉगिन त्रुटि",
      registerPrompt: "खाता नहीं है?",
      loginPrompt: "क्या आपके पास पहले से एक खाता मौजूद है?",
      phonePlaceholder: "10-अंकीय फोन नंबर",
      regionPlaceholder: "जैसे, उत्तर कर्नाटक",
      districtPlaceholder: "जैसे, धारवाड़",
      nameRequired: "नाम आवश्यक है",
      emailRequired: "ईमेल आवश्यक है",
      phoneRequired: "फोन आवश्यक है",
      regionRequired: "क्षेत्र आवश्यक है",
      districtRequired: "जिला आवश्यक है",
      passwordRequired: "पासवर्ड आवश्यक है",
      passwordMatchError: "पासवर्ड मेल नहीं खाते",
      registering: "पंजीकरण हो रहा है...",
      registrationFailed: "पंजीकरण विफल",
      registrationError: "पंजीकरण त्रुटि",

      // Crop Recommendation Form
      enterDetails: "अपने खेत का विवरण दर्ज करें",
      selectSoil: "मिट्टी का प्रकार चुनें",
      selectRainfall: "वर्षा सीमा चुनें",
      temperature: "तापमान (°C)",
      rainfall: "अपेक्षित वर्षा (मिमी)",
      recommendedCrops: "अनुशंसित फसलें",
      bestSeason: "सर्वश्रेष्ठ मौसम",
      waterRequirements: "जल आवश्यकता",
      harvestDays: "कटाई के दिन",
      profitMargin: "लाभ मार्जिन",

      // Admin Dashboard
      adminDashboard: "प्रशासक डैशबोर्ड",
      logoutBtn: "लॉगआउट",
      totalCrops: "कुल फसलें",
      totalStores: "कुल दुकानें",
      seedsStat: "बीज",
      manageContent: "सामग्री प्रबंधित करें",
      addCrop: "फसल जोड़ें",
      addSeed: "बीज जोड़ें",
      addStore: "दुकान जोड़ें",

      // User Management
      userName: "उपयोगकर्ता नाम",
      userEmail: "उपयोगकर्ता ईमेल",
      userStatus: "उपयोगकर्ता स्थिति",
      joinDate: "शामिल होने की तारीख",
      lastActive: "अंतिम सक्रिय",
      userRole: "उपयोगकर्ता भूमिका",
      farmer: "किसान",
      active: "सक्रिय",
      inactive: "निष्क्रिय",
      blocked: "अवरुद्ध",

      // Profile Page
      profileDetails: "प्रोफाइल विवरण",
      farmLocation: "खेत का स्थान",
      farmSize: "खेत का आकार",
      primaryCrop: "प्राथमिक फसल",
      soilInfo: "मिट्टी की जानकारी",
      contactInfo: "संपर्क जानकारी",
      location: "स्थान",
      state: "राज्य",
      city: "शहर",
      notSet: "सेट नहीं है",
      na: "लागू नहीं",

      // About Page
      ourMission: "हमारा मिशन",
      missionStatement: "हमारा उद्देश्य कर्नाटक के किसानों को मिट्टी की स्थिति, मौसम के पैटर्न और बाजार के रुझानों के आधार पर सटीक सिफारिशें प्रदान करके फसल की खेती के बारे में सूचित निर्णय लेने में मदद करना है।",
      howItWorks: "यह कैसे काम करता है",
      soilAnalysisTitle: "मिट्टी का विश्लेषण",
      soilAnalysisDesc: "अपनी मिट्टी के प्रकार और पोषक तत्वों के आधार पर सिफारिशें प्राप्त करें",
      weatherDataTitle: "मौसम का डेटा",
      weatherDataDesc: "इष्टतम रोपण के लिए स्थानीय मौसम के पैटर्न पर विचार करें",
      marketTrendsTitle: "बाजार के रुझान",
      marketTrendsDesc: "वर्तमान बाजार की मांगों और कीमतों के साथ अपडेट रहें",

      // Crop Details
      soilTypeInfo: "मिट्टी का प्रकार",
      harvestSeason: "कटाई का मौसम",
      waterNeed: "जल की आवश्यकता",
      fertilizer: "खाद",
      pestControl: "कीट नियंत्रण",
      diseasePrevention: "रोग की रोकथाम",
      yieldPotential: "उपज क्षमता",
      marketPrice: "बाजार मूल्य",
      transportationCost: "परिवहन लागत",
      storageInfo: "भंडारण जानकारी",
      processingRequired: "प्रसंस्करण आवश्यक",

      // Seed Details
      seedBrand: "बीज ब्रांड",
      seedType: "बीज प्रकार",
      purityLevel: "शुद्धता स्तर",
      viability: "व्यवहार्यता",
      packSize: "पैक साइज",
      expiryDate: "समाप्ति तारीख",
      stockAvailable: "स्टॉक उपलब्ध",
      supplierInfo: "आपूर्तिकर्ता जानकारी",
      minimumOrder: "न्यूनतम ऑर्डर",
      deliveryTime: "डिलीवरी समय",

      // Store Details
      storeName: "दुकान का नाम",
      storeAddress: "दुकान का पता",
      storePhone: "दुकान फोन",
      storeEmail: "दुकान ईमेल",
      storeHours: "दुकान के घंटे",
      openingTime: "खुलने का समय",
      closingTime: "बंद होने का समय",
      productsAvailable: "उपलब्ध उत्पाद",
      deliveryAvailable: "डिलीवरी उपलब्ध",
      onlineOrdering: "ऑनलाइन ऑर्डरिंग",

      // Messages & Alerts
      failedLoadRecommendations: "सिफारिशें प्राप्त करने में विफल। कृपया पुनः प्रयास करें।",
      tryAgain: "फिर से प्रयास करें",
      loading: "लोड हो रहा है...",
      loadingData: "डेटा लोड हो रहा है...",
      dataLoading: "कृपया प्रतीक्षा करें, डेटा लोड हो रहा है...",

      // Form Fields
      submit: "सबमिट करें",
      submitForm: "फॉर्म सबमिट करें",
      cancel: "रद्द करें",
      save: "बचाएं",
      delete: "हटाएं",
      edit: "संपादित करें",
      update: "अपडेट करें",
      search: "खोज",
      filter: "फ़िल्टर",
      error: "त्रुटि",
      success: "सफल",
      warning: "चेतावनी",
      info: "जानकारी",
      close: "बंद करें",
      confirm: "पुष्टि करें",
      apply: "लागू करें",
      reset: "रीसेट करें",
      clear: "साफ़ करें",

      // Headers & Titles
      welcomeBack: "स्वागत है!",
      myProfile: "मेरी प्रोफाइल",
      help: "मदद",
      faq: "सामान्य प्रश्न",
      contactUs: "हमसे संपर्क करें",
      privacy: "गोपनीयता नीति",
      terms: "शर्तें और शिकायतें",

      // Soil Types
      redSoil: "लाल मिट्टी",
      blackSoil: "काली मिट्टी",
      alluvialSoil: "जलोढ़ मिट्टी",
      lateriteSoil: "लैटेराइट मिट्टी",
      sandySoil: "रेतीली मिट्टी",
      claySoil: "चिकनी मिट्टी",

      // Rainfall Ranges
      rainfallLow: "< 300 मिमी (कम)",
      rainfallMedium: "300 - 600 मिमी (मध्यम)",
      rainfallMediumHigh: "600 - 900 मिमी (मध्यम-उच्च)",
      rainfallHigh: "900 - 1200 मिमी (उच्च)",
      rainfallVeryHigh: "1200 - 1500 मिमी (बहुत उच्च)",
      rainfallExcessive: "> 1500 मिमी (अत्यधिक)",

      // Store Types
      kssclDepot: "केएसएससीएल डिपो",
      krishiVikasKendra: "कृषि विकास केंद्र",
      privateDealer: "निजी डीलर",
      cooperativeSociety: "सहकारी समिति",

      // Admin Management
      cropManagement: "फसल प्रबंधन",
      manageCropDesc: "फसल डेटा जोड़ें, संपादित करें और हटाएं",
      existingCrops: "मौजूदा फसलें",
      showLess: "कम दिखाएं",
      showMore: "अधिक दिखाएं",
      days: "दिन",
      cropNameLabel: "फसल का नाम",
      selectSeason: "मौसम चुनें",
      selectWaterNeeds: "जल की आवश्यकताएं चुनें",
      suitableDistricts: "उपयुक्त जिले",
      fertilizersPlaceholder: "जैसे, यूरिया, डीएपी, एनपीके",
      imageURL: "छवि URL",
      cropDescription: "विवरण",
      processing: "प्रोसेसिंग...",
      updateCrop: "फसल अपडेट करें",
      addCropBtn: "फसल जोड़ें",
      cropAddedSuccess: "फसल सफलतापूर्वक जोड़ी गई!",
      cropUpdateSuccess: "फसल सफलतापूर्वक अपडेट की गई!",
      cropDeleteSuccess: "फसल सफलतापूर्वक हटाई गई!",
      confirmDeleteCrop: "क्या आप वाकई इस फसल को हटाना चाहते हैं?",
      notAuthenticated: "प्रमाणित नहीं",
      loginAsAdminMsg: "सामग्री देखने और प्रबंधित करने के लिए कृपया व्यवस्थापक के रूप में लॉगिन करें।",
      goToAdminLogin: "व्यवस्थापक लॉगिन पर जाएं",
      seedManagement: "बीज प्रबंधन",
      manageSeedDesc: "बीज ब्रांड जोड़ें, देखें और हटाएं",
      existingSeeds: "मौजूदा बीज ब्रांड",
      seedNameLabel: "बीज का नाम (किस्म)",
      pricePerKg: "प्रति किलो कीमत (₹)",
      germinationRatePercent: "अंकुरण दर (%)",
      ratingStars: "रेटिंग (सितारे 0-5)",
      saving: "सहेजा जा रहा है...",
      updateSeed: "बीज अपडेट करें",
      addSeedBrand: "बीज ब्रांड जोड़ें",
      seedAddedSuccess: "बीज सफलतापूर्वक जोड़ा गया!",
      seedUpdateSuccess: "बीज सफलतापूर्वक अपडेट किया गया!",
      seedDeleteSuccess: "बीज सफलतापूर्वक हटाया गया!",
      confirmDeleteSeed: "क्या इस बीज ब्रांड को हटाना है?",
      errorSavingSeed: "बीज सहेजने में त्रुटि",
      storeManagement: "दुकान प्रबंधन",
      manageStoreDesc: "कृषि दुकानों और आपूर्तिकर्ताओं को प्रबंधित करें",
      existingStores: "मौजूदा दुकानें",
      ownerName: "मालिक का नाम",
      contactNumber: "संपर्क नंबर",
      latitude: "अक्षांश",
      longitude: "देशांतर",
      productsAvailableLabel: "उपलब्ध उत्पाद",
      updateStore: "दुकान अपडेट करें",
      addStoreBtn: "दुकान जोड़ें",
      storeAddedSuccess: "दुकान सफलतापूर्वक जोड़ी गई!",
      storeUpdateSuccess: "दुकान सफलतापूर्वक अपडेट की गई!",
      storeDeleteSuccess: "दुकान सफलतापूर्वक हटाई गई!",
      confirmDeleteStore: "क्या आप वाकई इस दुकान को हटाना चाहते हैं?",
      errorAddingStore: "दुकान जोड़ने में त्रुटि",
      errorUpdatingStore: "दुकान अपडेट करने में त्रुटि",
      errorDeletingStore: "दुकान हटाने में त्रुटि",

      // Districts
      dist_Bagalkot: "बागलकोट",
      dist_Ballari: "बल्लारी",
      dist_Belagavi: "बेलगावी",
      dist_Bengaluru_Rural: "बेंगलुरु ग्रामीण",
      dist_Bengaluru_Urban: "बेंगलुरु शहरी",
      dist_Bidar: "बीदर",
      dist_Chamarajanagar: "चामराजनगर",
      dist_Chikkaballapura: "चिक्काबल्लापुरा",
      dist_Chikkamagaluru: "चिक्कमगलुरु",
      dist_Chitradurga: "चित्रदुर्ग",
      dist_Dakshina_Kannada: "दक्षिण कन्नड़",
      dist_Davanagere: "दावणगेरे",
      dist_Dharwad: "धारवाड़",
      dist_Gadag: "गदग",
      dist_Hassan: "हासन",
      dist_Haveri: "हावेरी",
      dist_Kalaburagi: "कलबुर्गी",
      dist_Kodagu: "कोडागु",
      dist_Kolar: "कोलार",
      dist_Koppal: "कोप्पल",
      dist_Mandya: "मांड्या",
      dist_Mysuru: "मैसूरु",
      dist_Raichur: "रायचूर",
      dist_Ramanagara: "रामनगर",
      dist_Shivamogga: "शिवमोग्गा",
      dist_Tumakuru: "तुमकुरु",
      dist_Udupi: "उडुपी",
      dist_Uttara_Kannada: "उत्तर कन्नड़",
      dist_Vijayapura: "विजयपुरा",
      dist_Yadgir: "यादगीर",
    },
    mr: {
      // Navigation
      home: "मुख्यपृष्ठ",
      about: "आमच्याबद्दल",
      profile: "प्रोफाइल",
      admin: "प्रशासक",
      login: "लॉगिन करा",
      register: "नोंदणी करा",
      logout: "लॉगआउट",
      learnMore: "अधिक जाणून घ्या",

      // Hero Section
      heroTitle: "कर्नाटकसाठी स्मार्ट शेती उपाय",
      heroSubtitle: "वैयक्तिक पीक शिफारसी मिळवा, दर्जेदार बियाणे शोधा आणि तुमच्या जवळची कृषी दुकाने शोधा",
      getStarted: "सुरुवात करा",
      smartFarmingTechnology: "स्मार्ट शेती तंत्रज्ञान",
      cropVarieties: "पीक वाण",
      storesListed: "दुकाने सूचीबद्ध",
      regionsCovered: "कव्हर केलेले प्रदेश",

      // Features
      features: "आमचे प्लॅटफॉर्म का निवडा?",
      feature1Title: "पीक शिफारस",
      feature1Desc: "मातीचा प्रकार, हवामान परिस्थिती आणि स्थानावर आधारित वैयक्तिक पीक सल्ला मिळवा",
      feature2Title: "बियाणे माहिती",
      feature2Desc: "विविध बियाणे वाण आणि त्यांच्या वैशिष्ट्यांबद्दल तपशीलवार माहिती मिळवा",
      feature3Title: "स्टोअर लोकेटर",
      feature3Desc: "जवळपासची कृषी दुकाने शोधा आणि दिशानिर्देश मिळवा",
      feature4Title: "उत्पन्न विश्लेषण",
      feature4Desc: "काळाच्या ओघात तुमच्या पीक उत्पादनाचा मागोवा घ्या आणि विश्लेषण करा",
      whyChooseTitle: "आमचे व्यासपीठ का निवडा?",
      whyChooseSubtitle: "उत्तम पीक व्यवस्थापनासाठी तंत्रज्ञानासह शेतकऱ्यांना सक्षम करणे",
      smartRecommendationsTitle: "स्मार्ट शिफारसी",
      smartRecommendationsDesc: "माती, हवामान आणि प्रादेशिक डेटावर आधारित एआय-सक्षम सूचना.",
      storeLocatorTitle: "स्टोअर लोकेटर",
      storeLocatorDesc: "सत्यापित पुनरावलोकनांसह आपल्या जवळची विश्वासार्ह कृषी दुकाने शोधा.",
      maximizeYieldTitle: "उत्पन्न वाढवा",
      maximizeYieldDesc: "उत्पादकता आणि नफा वाढवण्यासाठी पीक निवडीला अनुकूल करा.",
      trustedDataTitle: "विश्वासार्ह डेटा",
      trustedDataDesc: "कृषी संशोधन आणि वास्तविक शेतकरी अनुभवांद्वारे समर्थित.",

      // Quick Actions
      quickActions: "आता सुरुवात करा",
      action1Title: "पीक शिफारस मिळवा",
      action1Desc: "तुमच्या शेतासाठी सर्वोत्तम पिके शोधा",
      action2Title: "बियाणे शोधा",
      action2Desc: "योग्य बियाणे वाण शोधा",
      action3Title: "दुकाने शोधा",
      action3Desc: "तुमच्या जवळची कृषी दुकाने शोधा",
      readyToStart: "सुरू करण्यास तयार आहात?",
      joinFarmers: "दररोज हुशार पीक निर्णय घेणाऱ्या हजारो शेतकऱ्यांमध्ये सामील व्हा.",
      getRecommendationBtn: "तुमची शिफारस मिळवा →",
      footerRights: "पीक शिफारस प्रणाली — सर्व हक्क राखीव",

      // Crop Recommendation
      cropRecommendation: "पीक शिफारस",
      recommendationDesc: "तुमच्या शेताचे स्थान आणि परिस्थितीवर आधारित वैयक्तिक शिफारसी मिळवा",
      cropTab: "पीक शिफारस",
      seedTab: "बियाणे शोधक",
      storeTab: "स्टोअर लोकेटर",
      authRequired: "प्रमाणीकरण आवश्यक",
      loginMessage: "पीक शिफारसींमध्ये प्रवेश करण्यासाठी कृपया नोंदणी करा किंवा लॉगिन करा",
      enterTemp: "तापमान प्रविष्ट करा",
      match: "जुळणी",
      season: "हंगाम",
      duration: "कालावधी",
      waterNeeds: "पाण्याची गरज",
      fertilizers: "खते",
      expectedYield: "अपेक्षित उत्पन्न",
      noDataFound: "कोणताही डेटा सापडला नाही",

      // Seed Recommendation
      seedRecommendation: "बियाणे शिफारस",
      cropName: "पिकाचे नाव",
      enterCropName: "पिकाचे नाव प्रविष्ट करा (उदा. भुईमूग, कापूस, भात)",
      findSeeds: "बियाणे शोधा",
      seedVarieties: "बियाणे वाण",
      type: "प्रकार",
      brand: "ब्रँड",
      price: "किंमत",
      germination: "अंकुरण दर",
      features: "वैशिष्ट्ये",
      contactSupplier: "पुरवठादाराशी संपर्क साधा",
      quickSelect: "द्रुत निवड:",
      for: "साठी",
      enterCropToFind: "शिफारस केलेले बियाणे वाण शोधण्यासाठी पिकाचे नाव प्रविष्ट करा.",

      // Store Recommendation
      storeRecommendation: "स्टोअर लोकेटर",
      district: "जिल्हा",
      selectDistrict: "जिल्हा निवडा",
      storeType: "दुकानाचा प्रकार",
      selectType: "सर्व प्रकार",
      findStores: "दुकाने शोधा",
      noStoresFound: "तुमच्या निवडीसाठी कोणतीही दुकाने सापडली नाहीत",
      address: "पत्ता",
      contact: "संपर्क",
      allStores: "सर्व दुकाने",
      nearbyStores: "जवळपासची दुकाने",
      in: "मध्ये",
      govtApproved: "सरकारने मंजूर केलेले",
      timing: "वेळ",
      products: "उत्पादने",
      availableSeeds: "उपलब्ध बियाणे:",
      reviews: "पुनरावलोकने",
      noStoresInDistrict: "{district} मध्ये कोणतीही दुकाने सापडली नाहीत. वेगळा जिल्हा निवडण्याचा प्रयत्न करा.",
      selectDistrictPrompt: "जवळपासची दुकाने शोधण्यासाठी कृपया जिल्हा निवडा.",
      getDirections: "दिशानिर्देश मिळवा",
      callStore: "दुकानाला कॉल करा",

      // Profile
      personalInfo: "वैयक्तिक माहिती",
      name: "नाव",
      email: "ईमेल",
      phone: "फोन",
      soilType: "मातीचा प्रकार",
      recommendationHistory: "शिफारस इतिहास",
      history: "इतिहास",
      details: "तपशील",
      settings: "सेटिंग्ज",

      // Admin
      dashboard: "डॅशबोर्ड",
      totalUsers: "एकूण वापरकर्ते",
      recommendations: "शिफारसी",
      crops: "सक्रिय पिके",
      stores: "नोंदणीकृत दुकाने",
      manageUsers: "वापरकर्ते व्यवस्थापित करा",
      manageCrops: "पिके व्यवस्थापित करा",
      manageStores: "दुकाने व्यवस्थापित करा",
      users: "वापरकर्ते",
      adminPanel: "प्रशासक पॅनेल",
      defaultCredentials: "डीफॉल्ट क्रेडेंशियल्स: admin@gmail.com / admin123",
      registeredUsers: "नोंदणीकृत वापरकर्ते",
      role: "भूमिका",
      actions: "क्रिया",
      confirmDeleteUser: "तुम्हाला खात्री आहे की तुम्ही हा वापरकर्ता हटवू इच्छिता?",
      addNewContent: "नवीन सामग्री जोडा",
      selectContentToAdd: "तुम्हाला सिस्टममध्ये काय जोडायचे आहे ते निवडा",
      addCropDesc: "आवश्यकतांसह नवीन पीक डेटा जोडा",
      addStoreDesc: "संपर्क माहितीसह कृषी दुकाने जोडा",
      addSeedDesc: "विश्वसनीयता स्कोअरसह बियाणे ब्रँड जोडा",
      backToAll: "सर्वांवर परत जा",

      // Auth
      fullName: "पूर्ण नाव",
      password: "पासवर्ड",
      confirmPassword: "पासवर्डची पुष्टी करा",
      region: "प्रदेश",
      alreadyAccount: "आधीच खाते आहे?",
      noAccount: "खाते नाही?",
      registerHere: "येथे नोंदणी करा",
      loginHere: "येथे लॉगिन करा",
      userLogin: "वापरकर्ता लॉगिन",
      adminLogin: "प्रशासक लॉगिन",
      enterEmail: "कृपया वैध ईमेल पत्ता प्रविष्ट करा.",
      passwordLengthError: "पासवर्ड किमान 6 वर्णांचा असावा.",
      loginFailed: "लॉगिन अयशस्वी",
      loginError: "लॉगिन त्रुटी",
      registerPrompt: "खाते नाही?",
      loginPrompt: "आधीच खाते आहे?",
      phonePlaceholder: "10-अंकी फोन नंबर",
      regionPlaceholder: "उदा., उत्तर कर्नाटक",
      districtPlaceholder: "उदा., धारवाड",
      nameRequired: "नाव आवश्यक आहे",
      emailRequired: "ईमेल आवश्यक आहे",
      phoneRequired: "फोन आवश्यक आहे",
      regionRequired: "प्रदेश आवश्यक आहे",
      districtRequired: "जिल्हा आवश्यक आहे",
      passwordRequired: "पासवर्ड आवश्यक आहे",
      passwordMatchError: "पासवर्ड जुळत नाहीत",
      registering: "नोंदणी करत आहे...",
      registrationFailed: "नोंदणी अयशस्वी",
      registrationError: "नोंदणी त्रुटी",

      // Crop Recommendation Form
      enterDetails: "तुमच्या शेताचे तपशील प्रविष्ट करा",
      selectSoil: "मातीचा प्रकार निवडा",
      selectRainfall: "पावसाची श्रेणी निवडा",
      temperature: "तापमान (°C)",
      rainfall: "अपेक्षित पाऊस (मिमी)",
      recommendedCrops: "शिफारस केलेली पिके",
      bestSeason: "सर्वोत्तम हंगाम",
      waterRequirements: "पाण्याची आवश्यकता",
      harvestDays: "काढणीचे दिवस",
      profitMargin: "नफा मार्जिन",

      // Admin Dashboard
      adminDashboard: "प्रशासक डॅशबोर्ड",
      logoutBtn: "लॉगआउट",
      totalCrops: "एकूण पिके",
      totalStores: "एकूण दुकाने",
      seedsStat: "बियाणे",
      manageContent: "सामग्री व्यवस्थापित करा",
      addCrop: "पीक जोडा",
      addSeed: "बियाणे जोडा",
      addStore: "दुकान जोडा",

      // User Management
      userName: "वापरकर्ता नाव",
      userEmail: "वापरकर्ता ईमेल",
      userStatus: "वापरकर्ता स्थिती",
      joinDate: "सामील होण्याची तारीख",
      lastActive: "शेवटचे सक्रिय",
      userRole: "वापरकर्ता भूमिका",
      farmer: "शेतकरी",
      active: "सक्रिय",
      inactive: "निष्क्रिय",
      blocked: "अवरोधित",

      // Profile Page
      profileDetails: "प्रोफाइल तपशील",
      farmLocation: "शेताचे स्थान",
      farmSize: "शेताचा आकार",
      primaryCrop: "प्राथमिक पीक",
      soilInfo: "मातीची माहिती",
      contactInfo: "संपर्क माहिती",
      location: "स्थान",
      state: "राज्य",
      city: "शहर",
      notSet: "सेट केलेले नाही",
      na: "लागू नाही",

      // About Page
      ourMission: "आमचे ध्येय",
      missionStatement: "मातीची स्थिती, हवामानाचे नमुने आणि बाजारातील ट्रेंडच्या आधारे अचूक शिफारसी देऊन कर्नाटकच्या शेतकऱ्यांना पिकाच्या लागवडीबद्दल माहितीपूर्ण निर्णय घेण्यास मदत करणे हे आमचे ध्येय आहे.",
      howItWorks: "हे कसे कार्य करते",
      soilAnalysisTitle: "माती विश्लेषण",
      soilAnalysisDesc: "तुमच्या मातीचा प्रकार आणि पोषक घटकांवर आधारित शिफारसी मिळवा",
      weatherDataTitle: "हवामान डेटा",
      weatherDataDesc: "इष्टतम लागवडीसाठी स्थानिक हवामान नमुन्यांचा विचार करा",
      marketTrendsTitle: "बाजार ट्रेंड",
      marketTrendsDesc: "सध्याच्या बाजारातील मागण्या आणि किमतींसह अद्ययावत रहा",

      // Crop Details
      soilTypeInfo: "मातीचा प्रकार",
      harvestSeason: "काढणीचा हंगाम",
      waterNeed: "पाण्याची गरज",
      fertilizer: "खत",
      pestControl: "कीटक नियंत्रण",
      diseasePrevention: "रोग प्रतिबंध",
      yieldPotential: "उत्पन्न क्षमता",
      marketPrice: "बाजार भाव",
      transportationCost: "वाहतूक खर्च",
      storageInfo: "साठवण माहिती",
      processingRequired: "प्रक्रिया आवश्यक",

      // Seed Details
      seedBrand: "बियाणे ब्रँड",
      seedType: "बियाणे प्रकार",
      purityLevel: "शुद्धता पातळी",
      viability: "व्यवहार्यता",
      packSize: "पॅक आकार",
      expiryDate: "कालबाह्यता तारीख",
      stockAvailable: "स्टॉक उपलब्ध",
      supplierInfo: "पुरवठादार माहिती",
      minimumOrder: "किमान ऑर्डर",
      deliveryTime: "डिलिव्हरी वेळ",

      // Store Details
      storeName: "दुकानाचे नाव",
      storeAddress: "दुकानाचा पत्ता",
      storePhone: "दुकान फोन",
      storeEmail: "दुकान ईमेल",
      storeHours: "दुकान उघडण्याची वेळ",
      openingTime: "उघडण्याची वेळ",
      closingTime: "बंद होण्याची वेळ",
      productsAvailable: "उपलब्ध उत्पादने",
      deliveryAvailable: "डिलिव्हरी उपलब्ध",
      onlineOrdering: "ऑनलाइन ऑर्डरिंग",

      // Messages & Alerts
      failedLoadRecommendations: "शिफारसी मिळविण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
      tryAgain: "पुन्हा प्रयत्न करा",
      loading: "लोड होत आहे...",
      loadingData: "डेटा लोड होत आहे...",
      dataLoading: "कृपया प्रतीक्षा करा, डेटा लोड होत आहे...",

      // Form Fields
      submit: "सबमिट करा",
      submitForm: "फॉर्म सबमिट करा",
      cancel: "रद्द करा",
      save: "जतन करा",
      delete: "हटवा",
      edit: "संपादित करा",
      update: "अपडेट करा",
      search: "शोधा",
      filter: "फिल्टर",
      error: "त्रुटी",
      success: "यशस्वी",
      warning: "चेतावणी",
      info: "माहिती",
      close: "बंद करा",
      confirm: "पुष्टी करा",
      apply: "लागू करा",
      reset: "रीसेट करा",
      clear: "साफ करा",

      // Headers & Titles
      welcomeBack: "स्वागत आहे!",
      myProfile: "माझी प्रोफाइल",
      help: "मदत",
      faq: "सामान्य प्रश्न",
      contactUs: "आमच्याशी संपर्क साधा",
      privacy: "गोपनीयता धोरण",
      terms: "अटी आणि शर्ती",

      // Soil Types
      redSoil: "लाल माती",
      blackSoil: "काळी माती",
      alluvialSoil: "गाळाची माती",
      lateriteSoil: "जांभी माती",
      sandySoil: "वालुकामय माती",
      claySoil: "चिकणमाती",

      // Rainfall Ranges
      rainfallLow: "< 300 मिमी (कमी)",
      rainfallMedium: "300 - 600 मिमी (मध्यम)",
      rainfallMediumHigh: "600 - 900 मिमी (मध्यम-उच्च)",
      rainfallHigh: "900 - 1200 मिमी (उच्च)",
      rainfallVeryHigh: "1200 - 1500 मिमी (खूप उच्च)",
      rainfallExcessive: "> 1500 मिमी (अत्यधिक)",

      // Store Types
      kssclDepot: "केएसएससीएल डेपो",
      krishiVikasKendra: "कृषी विकास केंद्र",
      privateDealer: "खाजगी विक्रेता",
      cooperativeSociety: "सहकारी संस्था",

      // Admin Management
      cropManagement: "पीक व्यवस्थापन",
      manageCropDesc: "पीक डेटा जोडा, संपादित करा आणि हटवा",
      existingCrops: "अस्तित्वातील पिके",
      showLess: "कमी दाखवा",
      showMore: "अधिक दाखवा",
      days: "दिवस",
      cropNameLabel: "पिकाचे नाव",
      selectSeason: "हंगाम निवडा",
      selectWaterNeeds: "पाण्याची गरज निवडा",
      suitableDistricts: "योग्य जिल्हे",
      fertilizersPlaceholder: "उदा., युरिया, डीएपी, एनपीके",
      imageURL: "प्रतिमा URL",
      cropDescription: "वर्णन",
      processing: "प्रक्रिया करत आहे...",
      updateCrop: "पीक अपडेट करा",
      addCropBtn: "पीक जोडा",
      cropAddedSuccess: "पीक यशस्वीरित्या जोडले!",
      cropUpdateSuccess: "पीक यशस्वीरित्या अपडेट केले!",
      cropDeleteSuccess: "पीक यशस्वीरित्या हटवले!",
      confirmDeleteCrop: "तुम्हाला खात्री आहे की तुम्ही हे पीक हटवू इच्छिता?",
      notAuthenticated: "प्रमाणित नाही",
      loginAsAdminMsg: "सामग्री पाहण्यासाठी आणि व्यवस्थापित करण्यासाठी कृपया प्रशासक म्हणून लॉगिन करा.",
      goToAdminLogin: "प्रशासक लॉगिनवर जा",
      seedManagement: "बियाणे व्यवस्थापन",
      manageSeedDesc: "बियाणे ब्रँड जोडा, पहा आणि काढून टाका",
      existingSeeds: "अस्तित्वातील बियाणे ब्रँड",
      seedNameLabel: "बियाण्याचे नाव (वाण)",
      pricePerKg: "प्रति किलो किंमत (₹)",
      germinationRatePercent: "अंकुरण दर (%)",
      ratingStars: "रेटिंग (तारे 0-5)",
      saving: "जतन करत आहे...",
      updateSeed: "बियाणे अपडेट करा",
      addSeedBrand: "बियाणे ब्रँड जोडा",
      seedAddedSuccess: "बियाणे यशस्वीरित्या जोडले!",
      seedUpdateSuccess: "बियाणे यशस्वीरित्या अपडेट केले!",
      seedDeleteSuccess: "बियाणे यशस्वीरित्या हटवले!",
      confirmDeleteSeed: "हा बियाणे ब्रँड हटवायचा?",
      errorSavingSeed: "बियाणे जतन करण्यात त्रुटी",
      storeManagement: "दुकान व्यवस्थापन",
      manageStoreDesc: "कृषी दुकाने आणि पुरवठादार व्यवस्थापित करा",
      existingStores: "अस्तित्वातील दुकाने",
      ownerName: "मालकाचे नाव",
      contactNumber: "संपर्क क्रमांक",
      latitude: "अक्षांश",
      longitude: "रेखांश",
      productsAvailableLabel: "उपलब्ध उत्पादने",
      updateStore: "दुकान अपडेट करा",
      addStoreBtn: "दुकान जोडा",
      storeAddedSuccess: "दुकान यशस्वीरित्या जोडले!",
      storeUpdateSuccess: "दुकान यशस्वीरित्या अपडेट केले!",
      storeDeleteSuccess: "दुकान यशस्वीरित्या हटवले!",
      confirmDeleteStore: "तुम्हाला खात्री आहे की तुम्ही हे दुकान हटवू इच्छिता?",
      errorAddingStore: "दुकान जोडण्यात त्रुटी",
      errorUpdatingStore: "दुकान अपडेट करण्यात त्रुटी",
      errorDeletingStore: "दुकान हटवण्यात त्रुटी",

      // Districts
      dist_Bagalkot: "बागलकोट",
      dist_Ballari: "बल्लारी",
      dist_Belagavi: "बेळगाव",
      dist_Bengaluru_Rural: "बेंगळुरू ग्रामीण",
      dist_Bengaluru_Urban: "बेंगळुरू शहरी",
      dist_Bidar: "बिदर",
      dist_Chamarajanagar: "चामराजनगर",
      dist_Chikkaballapura: "चिक्काबल्लापुरा",
      dist_Chikkamagaluru: "चिक्कमगलुरू",
      dist_Chitradurga: "चित्रदुर्ग",
      dist_Dakshina_Kannada: "दक्षिण कन्नड",
      dist_Davanagere: "दावणगेरे",
      dist_Dharwad: "धारवाड",
      dist_Gadag: "गदग",
      dist_Hassan: "हासन",
      dist_Haveri: "हावेरी",
      dist_Kalaburagi: "कलबुर्गी",
      dist_Kodagu: "कोडागु",
      dist_Kolar: "कोलार",
      dist_Koppal: "कोप्पल",
      dist_Mandya: "मांड्या",
      dist_Mysuru: "म्हैसूर",
      dist_Raichur: "रायचूर",
      dist_Ramanagara: "रामनगर",
      dist_Shivamogga: "शिमोगा",
      dist_Tumakuru: "तुमकुरू",
      dist_Udupi: "उडुपी",
      dist_Uttara_Kannada: "उत्तर कन्नड",
      dist_Vijayapura: "विजयपुरा",
      dist_Yadgir: "यादगीर",
    }
  };

  const value = {
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || key
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider;